### ISSUE TITLE
Deployment succeded with 3 failures 

### ISSUE THREAD

**Issue by claytontx** [OfficeDev/microsoft-teams-apps-faqplus#103]
When deploying the ARM template, I got 3 errors and as the deployment guide says You will now see the following : 
Once the deployment has finished, you would be directed to a page that has the following fields:

botId - This is the Microsoft Application ID for the FAQ Plus bot.
appDomain - This is the base domain for the FAQ Plus Bot.
configurationAppUrl - This is the URL for the configuration web application.

I was not directed to this page.  I landed at the following page image attached - Your deployment is complete - with a link to go to the resource group.
![deployment-failures](https://user-images.githubusercontent.com/53943666/120684625-89a50880-c464-11eb-8793-3ac10f8995ed.png)
![deployment complete](https://user-images.githubusercontent.com/53943666/120684645-90cc1680-c464-11eb-8f4d-09035882575a.png)

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
