### ISSUE TITLE
LUIS Integration

### ISSUE THREAD

**Issue by cankanat** [OfficeDev/microsoft-teams-apps-faqplus#104]
How can I iplement the LUIS service to the FAQ bot? Is it possible?

**Comment by SubbaReddi** [comment]
Querying from QnAmaker is referred here: https://github.com/OfficeDev/microsoft-teams-apps-faqplus/blob/675c435fd0ea1695d37717a69f507f96602490f3/Source/Microsoft.Teams.Apps.FAQPlusPlus/Bots/FaqPlusPlusBot.cs#L787
And you may need to update the code to implement [LUIS](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=csharp)
