### ISSUE TITLE
FAQ Plus only deploys the expert bot to the general channel

### ISSUE THREAD

**Issue by cmack00** [OfficeDev/microsoft-teams-apps-faqplus#105]
I need a way to deploy the experts app to a channel other than the general channel

**Comment by SubbaReddi** [comment]
The channel ID for the General channel always matches the team ID.
When you save Team id in configuration app, it saves general channel id to database. So, expert messages will send to General channel.

You can try updating "ConfigurationInfo" table in storage account-> TeamId to required channel id
Hope it helps?

**Comment by jon-rizzo** [comment]
The config web site will not allow you to paste a channel ID - it will only accept a team ID.  As you suggested, I manually set it by updating the value in the storage table using Microsoft Azure Storage Explorer, but when I do that, it stops working in the General channel but still does not work in the channel that I tried to set it to.  So, it appears that only the general channel is supported.

**Comment by cmack00** [comment]
I experienced the same behavior, I change the ID in the config table and it broke the BOT service. So it'd be great if the dev team could build in that functionality in a future update.
