### ISSUE TITLE
Support for multiple question selection

### ISSUE THREAD

**Issue by bennope** [OfficeDev/microsoft-teams-apps-faqplus#107]
I have added a FAQ list to the knowledgebase. 
when I use the bot and ask a question where multiple questions with a confidence score over 30% are found the bot only returns one. When testing the KB and inpect the reply I am able to select and train another answer.
Is there any way to configure the bot so that it displays all found questions with a confidence score over x% and I can select one during the conversation with the bot?
this would be the behavior Power virtual agents have implemented.

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
