### ISSUE TITLE
Images in the Bot answers

### ISSUE THREAD

**Issue by cmack00** [OfficeDev/microsoft-teams-apps-faqplus#108]
When an experts uses the bot interface to create a new QnA pair, an image url can be specified and the preview shows the image correctly. When an end user asks the question, the answer shows a link where the image should be

**Comment by Mikhail2k15** [comment]
Your image URL should be publicly accessible on the Internet.

**Comment by cmack00** [comment]
The images are available o the inet, I am using images from the MS teams user guides actually. The image appears fine when we create the QnA pair but when the bot provides an answer to a user then the image is just a hyperlink and the image is not displayed unless the user clicks the link

**Comment by SubbaReddi** [comment]
Can you give screenshot of the response?

**Comment by cmack00** [comment]
Sure, Screenshot of the Bot reply is attached, I also added a screen shot of the QnA pair reply.
![Bot Image URL](https://user-images.githubusercontent.com/51133110/128750701-0655cbd5-e222-4f72-a03c-8190d8003098.JPG)
![Bot QnA pair](https://user-images.githubusercontent.com/51133110/128751109-093c72c5-bb8c-41df-86af-dcdd0c0d7e79.JPG)

**Comment by SubbaReddi** [comment]
@cmack00: It is expected behavior. It's not coded to display the image in adaptive card.
Here is the reference: https://github.com/OfficeDev/microsoft-teams-apps-faqplus/blob/675c435fd0ea1695d37717a69f507f96602490f3/Source/Microsoft.Teams.Apps.FAQPlusPlus/Cards/MessagingExtensionQnaCard.cs#L201
