### ISSUE TITLE
Users get welcome message twice

### ISSUE THREAD

**Issue by Mikhail2k15** [OfficeDev/microsoft-teams-apps-faqplus#109]
Users get a welcome message twice. Teams app setup policy was used. 
Repro steps:
- create a custom app setup policy
- add and pin the FAQPlus bot to the app setup policy
- add a user for the app setup policy 

![image](https://user-images.githubusercontent.com/11201670/123414560-b4463500-d5bc-11eb-8bbe-dfc9c37246cb.png)

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
