### ISSUE TITLE
No login-prompt in step 5 

### ISSUE THREAD

**Issue by Fledelius** [OfficeDev/microsoft-teams-apps-faqplus#11]
First of all, thanks for the very good deployment guide. It's really easy to understand.

I'm at the moment trying to deploy this FAQ-plus bot within my organiazation. I've got a problem in the deployment guide at step 5, where we should be able to finish the configuration app. When I go to the redirected URL at https://[BaseResourceName]-configuration.azure.net there is no prompt to login. As you can see in the picture below, the url is just just a normal web-app page. 
![Web app](https://user-images.githubusercontent.com/62646536/77528180-c8692700-6e8d-11ea-9ac3-ec8f07507e7c.png)

I've done the deployment guide multiple times within different resourcegroups and with different KB in QnAmaker. Every time I get to step 5, where I can't go further due to no login prompt. 

As a global administrator, I've also tried to grant admin consent in the API permissions within the configuration app as I saw that proposed in another troubleshoot. That didnt help either.  

I can't figure out where I've done something wrong. Hopefully one of you guys can help :-)

Best regards

**Comment by coderkrishna** [comment]
@Fledelius The full URL can either be `https://[BaseResourceName]-configuration.azurewebsites.net` or `https://[BaseResourceName]-config.azurewebsites.net`, and if the URL was not written as how I have written it, then I'll make sure that this update is made for the deployment guide

**Comment by Fledelius** [comment]
@coderkrishna Thanks for your reply. I think the deployment guide is fine, and thats not where my issue lies. 

As far as I understood, the right URL can always we be found in the App Service for the [BaseResourceName]-configuration/config app, right? 
In the App Registration I've redirected the configuration/config (either name is appropriate, right?) app's URL to my App Services URL - and thats https://[BaseResourceName]-config.azurewebsites.net

My issue is that when I go to that URL (https://[BaseResourceName]-config.azurewebsites.net), I dont get the prompt to login as it says in the deployment guide. It just shows the standard welcome webpage as I posted in my OP. 

It seems like are is no transition (lack of better words) from the App Registration-config to the URL, and I cant figure out where I went wrong. 

Thanks for your time.

**Comment by coderkrishna** [comment]
@Fledelius - Have you set up the authentication correctly? I am going through the deployment guide. Please share the screenshot of the configuration app registration, especially the authentication piece. I'm thinking you have not specified the Redirect URI there

**Comment by Fledelius** [comment]
@coderkrishna here is screenshot of the configuration app registration at the authentication piece. I redirected the URI to https://[BaseResorceName]config.azurewebsites.net as told in the guide. 
<img width="993" alt="SS faq" src="https://user-images.githubusercontent.com/62646536/77732803-f2455980-7005-11ea-8fae-e0e585d4afbd.png">

Appreciate your time.

**Comment by coderkrishna** [comment]
@Fledelius That looks good to me, can you also send me a screenshot of your resource group? I want to see the resources as well

**Comment by Fledelius** [comment]
Of course. Here you go
<img width="1362" alt="azure" src="https://user-images.githubusercontent.com/62646536/77853845-af8ea780-71e6-11ea-8f03-62238613d89b.png">

**Comment by v-smahaj** [comment]
We are not able to repro this issue at our end.
Let us know if issue is not resolved yet.
