### ISSUE TITLE
Unable to Install FAQ Plus bot

### ISSUE THREAD

**Issue by jamiemccarroll** [OfficeDev/microsoft-teams-apps-faqplus#110]
Currently having an issue when attempting to deploy bot for client.

We are getting an error saying Manifest Error when uploading through upload a custom app in teams:

Error while reading manifest.json: Invalid value(s) specified for validDomains[0]: "[Client bot Site Placeholder]"

And a separate message when attempting to install from app studio in teams where we got a continuous spinning wheel which is attempting to connect to a server point which it is unable to reach.

Can anyone please provide any further assistance and guidance in terms of what policy settings need to be in place on the client end in order for this to work?

**Comment by SubbaReddi** [comment]
Make sure Valid domains is in following format: "faqplusapp.azurewebsites.net"
Should not be like "**https://**faqplusapp.azurewebsites.net"
