### ISSUE TITLE
We can't upload this app because it's already in the catalog

### ISSUE THREAD

**Issue by cmack00** [OfficeDev/microsoft-teams-apps-faqplus#111]
I want to upload a 2nd instance of the FAQ plus for another business unit to use but when importing the packages the ID is the same in the manifest and generates the error "We can't upload this app because it's already in the catalog"

**Comment by Mikhail2k15** [comment]
In order to deploy the second instance, please generate in App Studio a new app id for your manifest and I would suggest changing packageName
![image](https://user-images.githubusercontent.com/11201670/124441488-62ec3180-dd84-11eb-80fc-70fe5608324f.png)

**Comment by cmack00** [comment]
The BOT uses two app packages, end user and experts. I used the ID from my app studio for the end user package, still needed one for the experts version though. For now I used a GUID generator tool and that seems to be working
