### ISSUE TITLE
Saving new KB results in "unable to reach app. Please try again"

### ISSUE THREAD

**Issue by leadfollowmove** [OfficeDev/microsoft-teams-apps-faqplus#118]
No recent changes to the deployment. Everything was working and now we get the above error when trying to add new KB's (on save) from the Experts Team. Rest of the Bot behaves normally.

Tried opening the associated App Service plan and restarting the related components (App, Config, FunctionApp and QnAMaker app) to no avail.

Will continue to investigate but appreciate any insights into what to check next.

Thanks.

**Comment by bungleweed** [comment]
Having the same issue. Did you manage to resolve this?
