### ISSUE TITLE
Installed but not working

### ISSUE THREAD

**Issue by jon-rizzo** [OfficeDev/microsoft-teams-apps-faqplus#119]
I went through a default template install (except for the names of the applications).  Both apps are installed.  However, the client application does not respond to anybody.  The experts app doesn't respond either (though I am a member of the expert team that I have it configured for).  The only clue that I have as to why neither app works is on the experts app.  It says "Unable to reach app.  Please try again.".    I triple-checked the tenant ID in the bot App Service configuration and it is indeed set to my tenant ID - the same tenant ID where the manifest was loaded into teams.  I suspect that somewhere there is a tenant ID value that is not getting set, because insights is reporting that the bot authentication is failing (it says "Failed to acquire token for client credentials." and it is referencing the default tenant ID instead of my tenant ID).  Is there anywhere else that I should look (other than the bot's App Service configuration) to make sure that my tenant ID is set properly?

![image](https://user-images.githubusercontent.com/42001610/126002449-d56ac847-6dc0-4777-ab4a-0e0973181586.png)

**Comment by kerravon67** [comment]
I am having the same issue.  DId you find a solution?  thx

**Comment by jon-rizzo** [comment]
In my particular case, it was happening because I had originally chosen to make the app single tenant.  When I switched the app registration to multitenant, it started working.  I didn't want to make it a multitenant app because of our internal policies (and because the service will only be used by people in my company), but it has to be multitenant because the knowledgebase is hosted by microsoft.

**Comment by kerravon67** [comment]
Yeah that was part of the problem. I changed the app to multi tenant and
some of it started working but the ask the expert and send feedback still
do not.

For some reason it is just not posting to the team with experts. Not sure
why.
