### ISSUE TITLE
Table formatting from QnA Maker does not translate to bot response

### ISSUE THREAD

**Issue by salnic** [OfficeDev/microsoft-teams-apps-faqplus#122]
Utilizing the table formatting feature to a question response displays appropriately in the QnA Maker. When published to FAQplus bot, it appears only as run-together text. Would like the bot to honor the formatting available in QnA Maker. Bulleted lists and B/I/U seem to come through fine.
![FAQplusBot](https://user-images.githubusercontent.com/87721914/126380842-74018ca8-6cc9-44cf-b6d5-6dbaa0e96d5e.png)
![QnAMaker](https://user-images.githubusercontent.com/87721914/126380850-5e05ebea-5598-4838-ada7-b5746b55bdc9.png)

**Comment by Mikhail2k15** [comment]
FAQPlus bot uses Adaptive Cards (AC) for rendering answers. AC doesn't support tables for text formatting. aka.ms/ACTextFeatures . As a workaround, you can try to build a table via AC columns programmatically. https://adaptivecards.io/explorer/Column.html
