### ISSUE TITLE
Change wording on customer facing expert transfer card.

### ISSUE THREAD

**Issue by tdenny171202** [OfficeDev/microsoft-teams-apps-faqplus#123]
How can I change the text on this card? I don't see how to in the manifest files anywhere. Tried uploading to the Dev Studio and App Studio within teams and I can't seem to get it done.

![Capture](https://user-images.githubusercontent.com/17555210/126392779-272ad231-d8bf-47cf-82b2-6d091ec748aa.PNG)

**Comment by Mikhail2k15** [comment]
Please take a look at resx files. https://github.com/OfficeDev/microsoft-teams-apps-faqplus/tree/master/Source/Microsoft.Teams.Apps.FAQPlusPlus/Properties
