### ISSUE TITLE
Error attempting to log into Config App

### ISSUE THREAD

**Issue by shanemeisner** [OfficeDev/microsoft-teams-apps-faqplus#124]
When attempting to log into the Configuration app ( https://Ourbotname-config.azurewebsites.net) we are receiving the following error:
AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption.

and when attempting to connect to the bot itself ( https://OurBotName.azurewebsites.net/) we get:

Internal Server Error:
An error occurred while starting the application.

Any ideas??

**Comment by Mikhail2k15** [comment]
@shanemeisner  please double-check the settings for your configuration app. It should be single-tenant with an implicit grant. config.azurewebsites.net

**Comment by shanemeisner** [comment]
Thanks for the reply.. The Config app is setup with Implicit grant and Single tenant:
![image](https://user-images.githubusercontent.com/67586976/127141684-6c2b0a5c-8b36-4f30-9986-4ec44e9b7a34.png)

one thing I did notice is that when we set this up we had it set as "Single-page Application", but noticed the documentation now say to set it up as Web: https://github.com/OfficeDev/microsoft-teams-apps-faqplus/wiki/Deployment-Guide#step-3-set-up-authentication-for-the-configuration-app

But if I try to remove https://ourcompanyfaqplus-config.azurewebsites.net from SPA and add it as web I get the following error:
 Failed to update FAQ Plus Configuration application. Error detail: Redirect URIs must have distinct values. [/tVVFakaXyDY1KCZGt4sRI]

**Comment by SubbaReddi** [comment]
@shanemeisner: Can you confirm if you are still facing the issue.
Once you remove from SPA and **save**, Add web redirect URI.

**Comment by shanemeisner** [comment]
I am still having the issue and am not sure if removing from SPA and adding as a Web redirect will break what is working?

The Bot itself is working in the Teams client. The only "broken" part is the configuration screen.. Everything in there is currently set correctly, but am concerned that at some point in the future we may need to update the settings and currently I can't get to that screen ( Step 5): https://github.com/OfficeDev/microsoft-teams-apps-faqplus/wiki/Deployment-Guide#step-5-finish-configuring-the-faq-plus-app

**Comment by shanemeisner** [comment]
@SubbaReddi  - Thank you!
 I am going on vacation, but will look to implement that change the week of August 23rd, and will reply once I have tested.

**Comment by shanemeisner** [comment]
@SubbaReddi  Thank you!!!! after removing the SPA and saving, then adding those URL's back in as Web based I am able to get to the config screen.
Thanks again,
Shane
