### ISSUE TITLE
Bot Question Telemetry?

### ISSUE THREAD

**Issue by kalanisanders** [OfficeDev/microsoft-teams-apps-faqplus#125]
We'd like to collect the questions that people are asking our bot so we can iterate on that information to update our KB. It looks like that should be in the customDimensions "text" field based on the documentation here: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-analytics-queries?view=azure-bot-service-4.0#schema-of-bot-analytics-instrumentation

Our customDimensions field has everything except "text". I'm assuming there's a setting somewhere to allow that to be logged, but didn't see anything in the bot docs or while rummaging around the source code.

Anyone have any idea how to get the messages or questions asked into the logs?

Thanks

**Comment by Mikhail2k15** [comment]
Please take a look at this article https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/get-analytics-knowledge-base?tabs=v1 and use <your-name>-qnamaker App Insights instance.
