### ISSUE TITLE
How to install 2 instances of the Faq Plus app

### ISSUE THREAD

**Issue by emiludev** [OfficeDev/microsoft-teams-apps-faqplus#134]
A client's request needs to deploy two Faq Plus installations, my question is it possible to have two Faq Plus instances in the same tenant? Is there an installation guide for a second Faq Plus instance?

Regards.

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
