### ISSUE TITLE
FAQPlus app not working after installation

### ISSUE THREAD

**Issue by PrajwalShambhu1990** [OfficeDev/microsoft-teams-apps-faqplus#138]
Hello everyone -

We are very interested to try out ad roll out FAQPlus chatbot internally in our organization. However, after the deployment the FAQPlus app is not working. FAQPlus Expert app doest even allow to add into the Teams channel. Please see below screenshots for your reference.

- Few things to highlight here, while all the steps mentioned in the deployment worked fine, except the last step of uploading the App menifesto package that was giving parsing error, despite tried via App Menifest editor. Therefore, what i did is we directly editied via App studio and updated the needed confif details and upload it for IT admin approval. Now that its approved, apparently the bot is not working, what are best troubleshooting steps in order to resolve this issue?

![image](https://user-images.githubusercontent.com/50304499/132013606-11fcd5e6-a042-49eb-8695-346f40bf2479.png)

![image](https://user-images.githubusercontent.com/50304499/132013693-e91c65bb-321e-4478-8535-af354291bd08.png)

Kindly appreciate your help.

Regards,
Prajwal

**Comment by User7522** [comment]
We are having the same issue. Have tried numerous deployments, the deployment is successful with no errors but the Bot doesn't respond with testing in Azure itself, nor MS Teams, and the config app does not add to MS Teams. I believe it shows a 400 error. Can anyone fix this?

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by User7522** [comment]
I'm no longer facing the issue because I've abandoned trying to use the FAQ Plus template and am instead going with QnA Maker bots directly and custom coding any necessary modifications. It would be nice however if this could get fixed for everyone else still trying to use it.
