### ISSUE TITLE
Null Deference 

### ISSUE THREAD

**Issue by appsec360** [OfficeDev/microsoft-teams-apps-faqplus#14]
File Name: MessagingExtensionQnaCard.cs
File Path: C:\user\MS-Teams\microsoft-teams-apps-faqplusv2-master\Source\Microsoft.Teams.Apps.FAQPlusPlus\Cards\MessagingExtensionQnaCard.cs

Vulnerable Parameter: userActions
Vulnerability:  @Line no 1092:  userActions is not checked for null value before being dereferenced

The method UpdateHistory() in MessagingExtensionQnaCard.cs can dereference a null-pointer on line 1092, thereby raising a NullException.

**Comment by rashmi-dixit** [comment]
Thank you for the feedback. I will share the suggestion with the concerned team.

**Comment by v-smahaj** [comment]
Thank you for reporting this, we have added it to our backlog of issues to fix.

**Comment by appsec360** [comment]
Please let me know that reported security issue is fixed or Not?
