### ISSUE TITLE
Setting up manifest files.

### ISSUE THREAD

**Issue by ClarkDRC** [OfficeDev/microsoft-teams-apps-faqplus#140]
I cannot find the manifest files mentioned in the instructions. Have they been renamed to just manifest.json?

**Comment by MujahidKhaiser** [comment]
They are inside the 'Manifest' folder.

**Comment by ClarkDRC** [comment]
The question is are they just called manifest.json? The instructions have them named differently.

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
