### ISSUE TITLE
No response from Bot

### ISSUE THREAD

**Issue by anees24** [OfficeDev/microsoft-teams-apps-faqplus#145]
QnA knowledge base is working fine online but in teams no response from bot!
![image](https://user-images.githubusercontent.com/82651338/137632024-bb80fe6b-ce24-48d6-abec-1f6bf356c1aa.png)

**Comment by jon-rizzo** [comment]
this started happening to us in just the past few days.  First, the bot disappeared entirely, as if it had been uninstalled, but then it returned as mysteriously as it disappeared and now it is unresponsive.

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
