### ISSUE TITLE
[Documentation Update] Steps mentioned in the deployment documentation is not in sync with actual folder structure.

### ISSUE THREAD

**Issue by jemjos** [OfficeDev/microsoft-teams-apps-faqplus#146]
Manifest folder has been updated with a new folder structure which include two different folder name **EndUser** and **SME** containing respective sample manifest.json, icon files as well as localization files. But in the deployment guide the same is not updated and **is referring to the old folder structure and file name**. 
![image](https://user-images.githubusercontent.com/82867244/138023475-61dab091-bd7d-4c47-b2a9-0c834f72a031.png)

Could you please go ahead and update the same to avoid confusions?

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
