### ISSUE TITLE
Response from faqplus different than qnamaker

### ISSUE THREAD

**Issue by jon-rizzo** [OfficeDev/microsoft-teams-apps-faqplus#147]
I have a Q&A pair that contains a unique word/phrase in the answer which is not present in the question (or in any other questions in my knowledgebase).  When I ask the faqplus bot a question that includes this word/phrase, it does not find the answer.  However, if I ask the same question using the "test" function of the qnamaker web site for my knowledge base, it finds the answer.   Can anybody explain what is happening here and how to bring the faqbot's answers in line with qnamaker?

**Comment by v-saikirang** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by jon-rizzo** [comment]
We are still facing this issue.

**Comment by gsv022** [comment]
Hi @jon-rizzo ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Kindly, let us know if you are still facing this issue and require assistance please log a new issue.
