### ISSUE TITLE
I have exactly same issue as "Images in the Bot answers #108"

### ISSUE THREAD

**Issue by nona020** [OfficeDev/microsoft-teams-apps-faqplus#149]
Hi, I have exactly the same issue in FAQ plus as above but I do not see what was the solution to fix from the conversation...
I can add images(link to public image on internet) save, test=> It is ok, I can see. 
But from FAQ plus, it does not show
![image](https://user-images.githubusercontent.com/93933448/140775101-fac569b7-0441-4b49-bff9-b92dcd978d9a.png)
but in FAQ plus it shows like this (text)
![image](https://user-images.githubusercontent.com/93933448/140775316-043ed9d4-da25-4510-b749-0f992b0565e7.png)

![image](https://user-images.githubusercontent.com/93933448/140775576-2253023b-6c45-4a1b-9664-6d8ece6b1a0c.png)
can anybody advise me ?

**Comment by gsv022** [comment]
Hi @nona020 ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Kindly, let us know if you are still facing this issue and require assistance please log a new issue.
