### ISSUE TITLE
We can't read the manifest file error

### ISSUE THREAD

**Issue by bchamnarnkit** [OfficeDev/microsoft-teams-apps-faqplus#150]
Hi Team, I am trying to upload the faq plus zip files into the teams admin center but facing error  "We can’t read the manifest file. Try again later." I've checked everything and not quite sure where the cause of the issue is 
![image](https://user-images.githubusercontent.com/84174370/142403013-6c3b9986-8fd3-42dd-8562-fa5f46088d85.png)

Any help would be appreciated! - Here is the manifest that I've used 

{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",
  "version": "1.0.0",
  "id": "aba30cfc-05df-4002-b956-a70996b12a54",
  "packageName": "com.microsoft.teams.faqplus",
  "developer": {
    "name": "Contoso",
    "websiteUrl": "https://www.microsoft.com",
    "privacyUrl": "https://privacy.microsoft.com/en-US/privacystatement",
    "termsOfUseUrl": "https://www.microsoft.com/en-us/legal/terms-of-use"
  },
  "localizationInfo": {
    "defaultLanguageTag": "en",
    "additionalLanguages": [
      {
        "languageTag": "en",
        "file": "en.json"
      },
      {
        "languageTag": "de",
        "file": "de.json"
      },
      {
        "languageTag": "fr",
        "file": "fr.json"
      },
      {
        "languageTag": "ar",
        "file": "ar.json"
      },
      {
        "languageTag": "ja",
        "file": "ja.json"
      },
      {
        "languageTag": "es",
        "file": "es.json"
      },
      {
        "languageTag": "he",
        "file": "he.json"
      },
      {
        "languageTag": "ko",
        "file": "ko.json"
      },
      {
        "languageTag": "pt-BR",
        "file": "pt-BR.json"
      },
      {
        "languageTag": "ru",
        "file": "ru.json"
      },
      {
        "languageTag": "zh-CN",
        "file": "zh-CN.json"
      },
      {
        "languageTag": "zh-TW",
        "file": "zh-TW.json"
      }
    ]
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "FAQ Plus"
  },
  "description": {
    "short": "A friendly FAQ bot that answers questions and connects you to experts.",
    "full": "A friendly question and answer bot that answers commonly asked questions. If it can't answer, it will put you in touch with an expert as soon as they are available."
  },
  "accentColor": "#64A2CC",
  "bots": [
    {
      "botId": "0c693422-ba9a-4c3b-a436-43c39611c72f",
      "scopes": [
        "personal",
        "team"
      ],
      "commandLists": [
        {
          "scopes": [
            "personal"
          ],
          "commands": [
            {
              "title": "Take a tour",
              "description": "Tour of key features"
            },
            {
              "title": "Ask an expert",
              "description": "Connect with an expert"
            },
            {
              "title": "Share feedback",
              "description": "Send feedback"
            }
          ]
        }
      ],
      "supportsFiles": false,
      "isNotificationOnly": false
    }
  ],
  "staticTabs": [
    {
      "entityId": "help",
      "name": "Help",
      "contentUrl": "https://chamnarnFAQrn.azurewebsites.net/help?theme={theme}",
      "scopes": [
        "personal"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "chamnarnFAQrn.azurewebsites.net"
  ]
}

**Comment by Porkai-Pandian** [comment]
Hi @bchamnarnkit,

Thanks for raising the issue with the app, can you please try removing the 'localizationInfo' all together from the manifest.json and uploaded it to the Teams again and let me know if it works.

**Comment by bchamnarnkit** [comment]
Seems to have done the trick. Thanks! - This is worth updating in the documentation as well
