### ISSUE TITLE
Where are the files to install it?

### ISSUE THREAD

**Issue by ecmansur** [OfficeDev/microsoft-teams-apps-faqplus#153]
Hi there!

When I read the deployment guide, I can see some missing images and when I download the zip file I can't find the files mentioned.
Am I doing anything wrong?

**Comment by MarcoVerbruggenVE** [comment]
I have the same problem. The current recommended deployment guide refers to files that do not exist in the github repository (deploy.ps1 and parameters.json in the Deployment folder)

**Comment by Porkai-Pandian** [comment]
Thank you for raising the issue, we're working with engineering team to address the documentation issue and broken images, will be able to correct as early as possible, will update this thread once the Wiki is updated

**Comment by tiagomiotto** [comment]
Found the Powershell in the feature/PowerShell deployment branch

**Comment by Porkai-Pandian** [comment]
This issue is addressed, closing the ticket, please create new issue if it still occurs.
