### ISSUE TITLE
When searching through unassigned cases, clicking on the searched case does not take you to original thread. 

### ISSUE THREAD

**Issue by gracesivaya** [OfficeDev/microsoft-teams-apps-faqplus#156]
In the messaging extension to search for Unassigned cases, when a user click on the search case, it does not take the user to the original thread. There is no action when clicking on the searched case. Is this a bug?

![FAQPlus-issue](https://user-images.githubusercontent.com/77342295/151097192-0ad885f6-2592-4510-b85f-dc6eb7c5d617.png)

This causes an issue when there are hundreds of unassigned cases and the expert team need to manual scroll through the channel posts to see which ones are unassigned.

**Comment by Porkai-Pandian** [comment]
Hi @gracesivaya,

Thank you for raising the query, can you please confirm the version of the app installed, is this something customized because I don't find this option.

**Comment by gracesivaya** [comment]
Hi Porkai,

It isn't customized,

You need to go to the Teams Channel for Expert Team where cases are posted, and find FAQ Plus messaging extension. I have attached the animation. Hope this helps.

Best Regards,
Grace Piyakorn S

**Comment by gracesivaya** [comment]
![FAQPlusIssue](https://user-images.githubusercontent.com/77342295/151469277-423b75e1-b1b0-446a-8c50-f7730f71f4c1.gif)
The animation of the issue.

**Comment by v-royavinash** [comment]
Hi @gracesivaya , 

This is not a issue with the FAQ plus but an ongoing issue with compose box for which the concerned team is working on it. 
A simple workaround to go to the original thread is shown below,

![Recording 2022-01-28 at 15 39 56](https://user-images.githubusercontent.com/94480537/151529335-130e091a-c110-4f13-832d-0fec85b22806.gif)


Let me know if it works for you.

**Comment by gracesivaya** [comment]
Thanks, @v-royavinash

**Comment by v-royavinash** [comment]
We have shared the required information hence closing the issue.
