### ISSUE TITLE
Inconsistency with localization and language

### ISSUE THREAD

**Issue by aidab98** [OfficeDev/microsoft-teams-apps-faqplus#157]
I'm deploying the bot in Arabic language and using the localization files in the folder.
1. I've changed the default culture in the azure deployment to ar.
2. I've changed the defaultlanguagetag to 'ar' in the manifest.
3. I've uploaded the manifest to Teams.

However, the language is inconsistent. Some buttons are in Arabic and others are in English.
I attempted to change in the manifest itself the command title and descriptions to Arabic, and this reflected in Teams in the commands part however the buttons are still in English.

How do I ensure that the cards and buttons are in Arabic only and not both. Bot should support multiple languages.

**Comment by Porkai-Pandian** [comment]
Hi @aidab98,

Thank you for posting the query, we already responded you over email, but posting it as well for benefit of others,

Below mentioned steps will change buttons text and other window texts to specific language. 
•	Change the default language while custom deployment of FAQ.
•	Change the default language field in the manifest before uploading the package.
•	Suggestion command can also be customized for specific language. For this you can update the highlighted command text in the manifest. 

 ![image](https://user-images.githubusercontent.com/87537966/152423415-026eac83-75cf-49e5-a89b-6a6533a1b896.png)

•	For changing the text of the buttons, you can change the MS Team’s language settings. 
 
![image](https://user-images.githubusercontent.com/87537966/152423435-2ce159f5-27e4-4a62-b573-bc00b60d9798.png)

After performing the above steps, you can find the texts in the specific language.

**Comment by gsv022** [comment]
Hi @aidab98 ,
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
