### ISSUE TITLE
Unexpected tenant id

### ISSUE THREAD

**Issue by rredert** [OfficeDev/microsoft-teams-apps-faqplus#16]
After following the deployment procedure for multiple times, I tend to run into the same issue. When trying to send a test message to the FAQ bot (using Azure bot management -> test in webchat) I keep receiving the error message "Unexpected tenant id". I verified the ARM deployment input parameters, and I indeed used the correct tenant ID. That is the Tenant ID under which all resources run. Any idea what could be causing this issue?

**Comment by abbodh** [comment]
Hi @rredert , can you please check and confirm whether the tenant where azure resources are hosted is the same as your Teams environment. The error can occur only if the tenant id's are mis-matched and can be fixed easily.
