### ISSUE TITLE
Get code changes from FTP

### ISSUE THREAD

**Issue by Emilianosanchezlopez** [OfficeDev/microsoft-teams-apps-faqplus#166]
**Teams Apps FaqPlus**

Hi, last year we deploy FaqPlus to a customer, we made several changes to the code like translating strings, adding some fields to chat extention, etc, we deploy this changes from FTP to Azure Web App.

Recently customer needs additional changes to the code, but we lost the modified code in a physical disk failure.

We proceeded to download the code from the Azure web App through FTP, but we don't see the previous  changes we made, 

Is there a way to obtain these changes in the code?

we are afraid of uploading the new changes and losing the previous ones.

In advance, thank you very much. 
Regards.

**Comment by Emilianosanchezlopez** [comment]
Thank you very much @Porkai-Pandian for your answer, we will try as soon as possible.
For now, we can close this issue.

**Comment by Emilianosanchezlopez** [comment]
Hi @Porkai-Pandian, hoping you are well, the client just gave me access to the resource group again, I followed the path you indicated and downloaded the repository, but I don't see the changes made in it, it's only the initial version of the code, is there another way to recover the changes I made before? 😭 

Thank you in advance.

**Comment by magurrapu** [comment]
@Emilianosanchezlopez  Thank you for your query. We are looking into it.
