### ISSUE TITLE
Options to change Teams channel Ask an Expert and Share feedback

### ISSUE THREAD

**Issue by mahybabu** [OfficeDev/microsoft-teams-apps-faqplus#17]
How do we change the Teams channel - one for Ask an Expert and another for Share feedback?
Because we have only one option in Config app for Teams ID which is used by both options - Ask an expert and Share feedback.

**Comment by prithvi7410** [comment]
Currently the app is configured in such a way that it posts both the query and feedback in General channel of team only. The feedback cannot be shared in separate channel.

**Comment by v-smahaj** [comment]
Thank you for reporting this. For FAQ Plus repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
