### ISSUE TITLE
Image from take a tour does not load

### ISSUE THREAD

**Issue by nona020** [OfficeDev/microsoft-teams-apps-faqplus#171]
I noticed that image is not working. (I think any image) here is the screen if you go to [take a tour]
In Prod, looks like image link is broken or so.
 
![image](https://user-images.githubusercontent.com/93933448/168549271-abb7b008-0ae3-4889-8aeb-0b27c0c8a7a7.png)

![image](https://user-images.githubusercontent.com/93933448/168549249-75a539a6-9ad9-453b-a7d1-480fdc6f5f9d.png)

I think this is the link to the image.
Can you give us advice what is wrong ?

**Comment by magurrapu** [comment]
@nona020 Thank you for your query. We are looking into it.

**Comment by gsv022** [comment]
Hi @nona020 ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
