### ISSUE TITLE
Manual deployment

### ISSUE THREAD

**Issue by peakers1976** [OfficeDev/microsoft-teams-apps-faqplus#176]
Hi,  I did a manual deployment as i was unable to deploy using the automated option.

All the steps were followed and the ARM template deployed successfully, the issue i have is when accessing the config page (configurationAppUrl )  for the expert web app it does not prompt me to authenticate and is not displaying the screen shown in the documentation. 

![image](https://user-images.githubusercontent.com/18456459/176591734-8b847a65-159d-456b-8bd5-66d9cba16e00.png)

Any ideas why this might be the case, i configured the app registration in azure ad as per the documentation. this is the land page i get when enter the configurationAppUrl  into the browser.

![image](https://user-images.githubusercontent.com/18456459/176591492-ea4fbb54-12ba-44a8-86e3-c93a03b823c4.png)

**Comment by Porkai-Pandian** [comment]
Hi @peakers1976, thank you for raising the query, can you confirm if you see the below screen once the deployment completed, the screenshot shared above meant some of the services are still deploying and not fully completed.

![image](https://user-images.githubusercontent.com/87537966/176741679-219ed08d-ed11-4bbb-a342-45d7af44b697.png)

**Comment by peakers1976** [comment]
> Hi @peakers1976, thank you for raising the query, can you confirm if you see the below screen once the deployment completed, the screenshot shared above meant some of the services are still deploying and not fully completed.
> 
> ![image](https://user-images.githubusercontent.com/87537966/176741679-219ed08d-ed11-4bbb-a342-45d7af44b697.png)

**Comment by peakers1976** [comment]
Hi @Porkai-Pandian, thank you for the follow-up, yes the screenshot you are referring to does show up 

![image](https://user-images.githubusercontent.com/18456459/176811206-1a6f2eca-600d-4000-8070-243dba55b9ae.png)

**Comment by peakers1976** [comment]
Hi @Porkai-Pandian , Just an update, I re-ran the ARM template again doing exactly what I had done previously and this time the configuration page prompts me for a sign-in and displays the config page.

![image](https://user-images.githubusercontent.com/18456459/176812330-8fc51ade-d757-45fc-8dc5-268c1ecbf6df.png)
