### ISSUE TITLE
App deploy failed: library could not be resolved by the "cdnjs" provider

### ISSUE THREAD

**Issue by blackchoey** [OfficeDev/microsoft-teams-apps-faqplus#177]
I'm using the latest code on master branch. When I follow the deployment guide, the following 2 web app deployment failed during ARM deployment:
![image](https://user-images.githubusercontent.com/16605901/180247490-39a84d4d-09d4-481c-a757-bb59211ee3c2.png)

Based on the logs in Azure Web App deployment center, the detailed error is:
```
libman.json : error LIB002: The "jquery-validation-unobtrusive@3.2.11" library could not be resolved by the "cdnjs" provider [C:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Microsoft.Teams.Apps.FaqPlusPlus.Configuration.csproj]
libman.json : error LIB002: The "jquery-validate@1.19.1" library could not be resolved by the "cdnjs" provider [C:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Microsoft.Teams.Apps.FaqPlusPlus.Configuration.csproj]
```

I also tried to build the app in my dev machine and same error occurred.

**Comment by samuel-pradhan-embee** [comment]
I am also facing the same error  with latest code.
![image](https://user-images.githubusercontent.com/81224711/180439579-94670962-ab4c-4111-b72a-c325170e76a0.png)

libman.json : error LIB002: The "jquery@3.4.1" library could not be resolved by the "cdnjs" provider 
libman.json : error LIB002: The "modernizr@2.8.3" library could not be resolved by the "cdnjs" provider
libman.json : error LIB002: The "jquery-validation-unobtrusive@3.2.11" library could not be resolved by the "cdnjs" 
libman.json : error LIB002: The "jquery-validate@1.19.1" library could not be resolved by the "cdnjs" provider

**Comment by Porkai-Pandian** [comment]
Hi @blackchoey,

Thank you for raising the issue, we're looking into the issue

**Comment by blackchoey** [comment]
Is there any update on this?

**Comment by v-royavinash** [comment]
@blackchoey Thanks for your patience. We are still analyzing it at our end and suspecting it to a bug. We will keep you posted with the updates/fixes.

**Comment by blackchoey** [comment]
Hi @v-royavinash 
Is there any update on this? I saw other people are facing similar issue: https://github.com/OfficeDev/microsoft-teams-apps-faqplus/issues/179

**Comment by v-royavinash** [comment]
@blackchoey We have identified it as a bug and currently testing the fix. We will release the fix post testing and keep you posted.

**Comment by gsv022** [comment]
Hi @blackchoey ,
Please follow the below steps:-

- Go to azure portal-->Click on resource group-->App Service-->Deployment Center-->**SYNC**
<img width="940" alt="image" src="https://user-images.githubusercontent.com/98143492/185079710-48e79392-1cb7-4a51-a279-5a320b470a38.png">

- Once the app service is successful. Please proceed with the remaining steps of deployment.  

Keep us posted.

**Comment by frankqianms** [comment]
Hi @gsv022, 
Thans for your advice, but it does not work for me, as get error status in the log.
<img width="980" alt="image" src="https://user-images.githubusercontent.com/109947924/185290052-a0eb28c9-4448-42a0-ba5b-837171a0b2b2.png">

Best regards,
Frank

**Comment by v-royavinash** [comment]
@frankqianms , Can you please click on the blue highlighted (Commit ID) link and share us the logs?

**Comment by frankqianms** [comment]
Sure. Here is the log, and I think the most important information is in the red box: some libraries can not be resolved.
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/109947924/185563871-7c7ecce6-d25a-49da-891a-c504ad7e24e6.png">

**Comment by v-royavinash** [comment]
@frankqianms, The logs shows the package versions are still pointing to the older versions not the one we pushed.

Could you please share the repo URL that is used for deployment. You can click on the "Settings" tab in the above screenshot and check the URL.

If its pointing to https://github.com/OfficeDev/microsoft-teams-apps-faqplus.git , please click again  on SYNC to take the latest changes.

**Comment by frankqianms** [comment]
@v-royavinash It works! Actually, we locally download this repo code and point to our url. Finally we found that some packages need to be upgraded. Please close it. Thanks a lot!
