### ISSUE TITLE
ARM deployment issue with Conficlt 

### ISSUE THREAD

**Issue by rahulsnc3it** [OfficeDev/microsoft-teams-apps-faqplus#179]
When trying to deploy the App through ARM template we are getting conflict error on Web App and Web App Config App service.

![ErrorSevadesk](https://user-images.githubusercontent.com/54054761/183838953-c1b18537-7dbb-44d6-9bc6-4b344e1fd782.png)

**Comment by v-royavinash** [comment]
@rahulsnc3it , Can you please go to the resource group --> App service --> Deployment center --> Logs and share us the entire logs for better understanding of the issue. 

![image](https://user-images.githubusercontent.com/94480537/183982421-dad9ee16-6e7e-4fdb-aa65-7a486560a676.png)

**Comment by rahulsnc3it** [comment]
Below are the logs details Even tried to redeploy but same error



ca286de
Porkai
Failed
Update msbuild version (#168)

Log Details
Commit ID: ca286de571753936514c47c9708e936f1ce5c48f


Updating submodules.

Preparing deployment for commit id 'ca286de571'.

Running custom deployment command...

Running deployment command...
Show Logs...

Deployment Failed.
Command: deploy.cmd
Handling .NET Web Application deployment.
Using Msbuild from 'C:\Program Files (x86)\MSBuilds\17.2.0\MSBuild\Current\Bin'.
All packages listed in packages.config are already installed.
Assets file has not changed. Skipping assets file writing. Path: C:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus\obj\project.assets.json
Assets file has not changed. Skipping assets file writing. Path: C:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.Common\obj\project.assets.json
Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus\Microsoft.Teams.Apps.FAQPlusPlus.csproj (in 458 ms).
Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.Common\Microsoft.Teams.Apps.FAQPlusPlus.Common.csproj (in 450 ms).
Assets file has not changed. Skipping assets file writing. Path: C:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.AzureFunction\obj\project.assets.json
Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.AzureFunction\Microsoft.Teams.Apps.FAQPlusPlus.AzureFunction.csproj (in 78 ms).

NuGet Config files used:
    D:\DWASFiles\Sites\#1sevadeskap-config\AppData\NuGet\NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
3 of 4 projects are up-to-date for restore.
  
  Restore operation started...
libman.json : error LIB002: The "jquery@3.4.1" library could not be resolved by the "cdnjs" provider [C:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Microsoft.Teams.Apps.FaqPlusPlus.Configuration.csproj]
libman.json : error LIB002: The "modernizr@2.8.3" library could not be resolved by the "cdnjs" provider [C:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Microsoft.Teams.Apps.FaqPlusPlus.Configuration.csproj]
libman.json : error LIB002: The "jquery-validation-unobtrusive@3.2.11" library could not be resolved by the "cdnjs" provider [C:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Microsoft.Teams.Apps.FaqPlusPlus.Configuration.csproj]
libman.json : error LIB002: The "jquery-validate@1.19.1" library could not be resolved by the "cdnjs" provider [C:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Microsoft.Teams.Apps.FaqPlusPlus.Configuration.csproj]
  
  One or more libraries failed to restore
  
Failed exitCode=1, command="C:\Program Files (x86)\MSBuilds\17.2.0\MSBuild\Current\Bin\MSBuild.exe" "C:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Microsoft.Teams.Apps.FaqPlusPlus.Configuration.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="C:\local\Temp\8da7a9f23775ce5";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="C:\home\site\repository\Source\\"
An error has occurred during web site deployment.
\r\nC:\Program Files (x86)\SiteExtensions\Kudu\97.40711.5827\bin\Scripts\starter.cmd deploy.cmd

**Comment by gsv022** [comment]
Hi @rahulsnc3it ,

Please follow the below steps:-

- Go to azure portal-->Click on resource group-->App Service-->Deployment Center-->**SYNC**
<img width="940" alt="image" src="https://user-images.githubusercontent.com/98143492/185079710-48e79392-1cb7-4a51-a279-5a320b470a38.png">

- Once the app service is successful. Please proceed with the remaining steps of deployment.  

Keep us posted.

**Comment by rahulsnc3it** [comment]
Thank you for able to deploy the services now.
