### ISSUE TITLE
QnA Maker Retiring - Can't make new after Oct 1, 2022 - Plan for FAQPlus?

### ISSUE THREAD

**Issue by npherson** [OfficeDev/microsoft-teams-apps-faqplus#181]
Hello! The documentation for QnA Maker says that it is being retired in favor of Azure Cognitive Service for Language and that after October 1st, 2022, you won't be able to create new QnA Maker resources in Azure.

https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/Overview/overview

Will this solution be updated to leverage Azure Cognitive Services or is it being retired?

**Comment by v-royavinash** [comment]
@npherson , Thanks for highlighting this. We have already has make a note and planned the migration. Any new QnA deployment will not work post 1st October, however it will still support the already deployed apps. 
We will keep you posted will the release and updates.

**Comment by timoleo23** [comment]
Hi @v-royavinash do you have an update on dates and migrations instructions for existing and new deployments ?

**Comment by v-royavinash** [comment]
Hi @timoleo23 , As of now there is not specific timeline defined for the new version of app. However this is on our highest priority. There is some dependency on the SDK side which we are following up internally. Be assured we will release the new version of app as soon as possible.

**Comment by gsv022** [comment]
Hi @npherson ,
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with FAQ-Plus please raise a new issue for further assistance.
