### ISSUE TITLE
Runtime Error on Configuration 

### ISSUE THREAD

**Issue by gmparky** [OfficeDev/microsoft-teams-apps-faqplus#183]
We are getting the following runtime message when trying to access the Configuration Webpage

![image](https://user-images.githubusercontent.com/40665509/186118051-bb8d7724-bb5d-431d-96ff-0425e0155e70.png)

**Comment by gsv022** [comment]
Hi @gmparky,
Thanks for raising the issue. We will look into this and get back to you with proper response soon.

**Comment by v-royavinash** [comment]
@gmparky , Could you share the FAQ deployment logs to check if the deployment was successful. Also why exactly you are trying to access the above URL?

**Comment by gmparky** [comment]
@v-royavinash we need to access that as part of the Deployment set up, Step 3 - Finish configuring the FAQ Plus app

[deployment_operations.zip](https://github.com/OfficeDev/microsoft-teams-apps-faqplus/files/9414075/deployment_operations.zip)

**Comment by gsv022** [comment]
Hi @gmparky ,

- The logs that has been shared seems to be fine. Could you please let us know what is the error that you are getting at the teams side and supporting screenshot would be more helpful. 
- And why exactly you are trying to access the above URL?

**Comment by gmparky** [comment]
@gsv022 I haven't got to Teams bit yet I am trying to access the URL to enter the configuration details for Teams. I am trying to access it it as I mentioned above - **Step 3  - Finish configuring the FAQ Plus app.**  

This is the step after setting up the QnA

**Comment by gsv022** [comment]
Hi @gmparky ,
Please make sure that deployment is successful and If there is any issue while running the UI side, please share the issue details and supporting screenshots would more helpful.

**Comment by gmparky** [comment]
Hi @gsv022,

Sorry I don't understand what you are asking, yes the deployment was successful as you can see from the logs I shared unless it's different logs you need. Also the first post is the screen shot of the UI when we go to the link as described in -Step 3. I don't get the App page I get the run time error on my first post. 

![image](https://user-images.githubusercontent.com/40665509/187713463-32b137c0-d4ee-41e7-b1ef-83e5f75ad91d.png)


So sorry I don't understand what is missing.

**Comment by gsv022** [comment]
Hi @gmparky ,

Please give us sometime as we are working on this and will get back to you with proper response soon.

Thank you.

**Comment by gsv022** [comment]
Hi @gmparky ,
Could you please share the MS teams Id so that we can discuss more on the issue.

**Comment by gmparky** [comment]
I haven't entered a Teams ID as the configuration site has the run time error? Don't want to post the full Team ID here on an open forum happy to share in private.

**Comment by gsv022** [comment]
Hi @gmparky ,
Could you please share us your MS Teams Id so that we can discuss internally over the teams chat

**Comment by gmparky** [comment]
graham.parkin@aggreko.co.uk

**Comment by gmparky** [comment]
gmparky@hotmail.com

**Comment by frankqianms** [comment]
Hi @gsv022 ,
I've encountered the same error. I want to know if there are any solutions for this now?

**Comment by gsv022** [comment]
Hi @gmparky ,
Please let us know if you  are still facing the issue.

**Comment by gmparky** [comment]
Yes this is still an issue, is there an update that we need to apply or a new deployment?

**Comment by gsv022** [comment]
Hi @gmparky ,
Thanks for the patience. It is found that this issue occurs due to incorrect configuration of configuration app i.e., either client Id or tenant Id is incorrect. Please cross- verify once.

Keep us posted.

**Comment by gmparky** [comment]
Hi @gsv022,

Yes we have checked this and it's correct it also was deployed via the script and as far as i can tell this all matches up.

**Comment by gsv022** [comment]
Hi @gmparky ,
This is my MS Teams Id:- v-saigattu@microsoft.com. Could you please share the screenshot of them to my teams.

**Comment by gmparky** [comment]
Shared as discussed

**Comment by gsv022** [comment]
@gmparky , we are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
