### ISSUE TITLE
Bot won't respond

### ISSUE THREAD

**Issue by cdzltung** [OfficeDev/microsoft-teams-apps-faqplus#184]
Hello, I seem to facing multiple issues. The first issue is that the user end bot won't reply to any messages, though there are topic suggestions as detailed on the manifest.json. There is no welcome message though, and it doesn't respond to anything typed.

For the expert side bot, for some reason it states that it can't connect to the app.

I've double checked all the steps and have done them twice, and I still can't figure out the issue.

I used the steps from 'Deployment Guide Manual' - or the manual deployment. Would this be avoided had I gone through the powershell deployment?

**Comment by gsv022** [comment]
Hi @cdzltung,
Thanks for raising the issue. Could you please share the teams id so that we can discuss the issue and will try to solve it over the call.

**Comment by cdzltung** [comment]
Here is the teams id (of where I tried installing the expert side app?): https://teams.microsoft.com/l/team/19%3a91d6dbdb5e3144809acc47a0af685bec%40thread.skype/conversations?groupId=2d765ad0-3306-4955-8cb3-c95d5cababef&tenantId=9cfbedc9-c7e4-46e2-be3e-d7fa81d0798a

I'm available to call any time today, thank you

**Comment by gsv022** [comment]
Hi @cdzltung ,
Could you please share your MS Teams id  so that we can discuss the issue and will try to solve it over the call.
