### ISSUE TITLE
FAQ Plus app GitHub repo

### ISSUE THREAD

**Issue by OlufemiOlaoye** [OfficeDev/microsoft-teams-apps-faqplus#187]
Unable to install the FAQ Plus app GitHub repo.

**Comment by gsv022** [comment]
Hi @OlufemiOlaoye ,
Could you please provide more details of the issue that you are facing and even supporting screenshots would be more helpful

Thank you.

**Comment by OlufemiOlaoye** [comment]
Thank you @gsv022 for the response.
See attached error messages I got.
[microsoft-teams-apps-faqplus-master.docx](https://github.com/OfficeDev/microsoft-teams-apps-faqplus/files/9493694/microsoft-teams-apps-faqplus-master.docx)

**Comment by OlufemiOlaoye** [comment]
Thank you @gsv022 for the response.
See attached error messages I got.
[Error.docx](https://github.com/OfficeDev/microsoft-teams-apps-faqplus/files/9494972/Error.docx)

**Comment by gsv022** [comment]
Hi @OlufemiOlaoye ,
Thanks for sharing the error document. We are working on it and will get back to you proper response soon.

**Comment by OlufemiOlaoye** [comment]
@gsv022 thanks for the update.

**Comment by pdl5p** [comment]
Any updates on this? I'm seeing the same issue.

**Comment by pdl5p** [comment]
I rolled back my version of the Azure CLI to 2.35.0 from https://github.com/Azure/azure-cli/releases and was able to run the deployment script successfully.

Apparently the cli has been recently migrated to different api which means there are breaking changes.

WARNING: The underlying Active Directory Graph API will be replaced by Microsoft Graph API in Azure CLI 2.37.0. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration.

The FAQ Plus deployment scripts will need updating to take this into account.

**Comment by v-royavinash** [comment]
@pdl5p  Thanks for sharing the info. @OlufemiOlaoye Could you please check Azure CLI version and try deploying using 2.35.0 version.
