### ISSUE TITLE
How to integrate an API to BOT

### ISSUE THREAD

**Issue by OlufemiOlaoye** [OfficeDev/microsoft-teams-apps-faqplus#188]
I need assistance on how to achieve this task in the attached screen recording.
[Screen Recording.zip](https://github.com/OfficeDev/microsoft-teams-apps-faqplus/files/9707556/Screen.Recording.zip)

When the "Ask an Expert" is click, it should be able to call an API.

Assistance needed urgently.

**Comment by v-royavinash** [comment]
Hi @OlufemiOlaoye , We won't be able to assist you with the customization of the app. However if you are looking for some specific feature please share us the details, post our internal review we will consider it for future releases.

Below is the link you can explore to handle any customization of the bot events. This might be helpful to call the API for your scenario, 
https://learn.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.teams.teamsactivityhandler?view=botbuilder-dotnet-stable

**Comment by gsv022** [comment]
Hi @OlufemiOlaoye ,
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with FAQ-Plus please raise a new issue for further assistance.
