### ISSUE TITLE
Runtime error when trying to load the config app service

### ISSUE THREAD

**Issue by AlanMRichards** [OfficeDev/microsoft-teams-apps-faqplus#19]
I get to the step in the deployment document that says to load the config app service but I get a runtime error.

It asks for a login and takes the details but then shows a runtime error page

**Comment by AmitKhot2508** [comment]
Hi @AlanMRichards, Could you please share screenshot and error details.

**Comment by nc-praveen** [comment]
Hi, I am getting this runtime error when accessing faqplus-config site. 

Server Error in '/' Application.

Runtime Error

Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine. 

Details: To enable the details of this specific error message to be viewable on remote machines, please create a <customErrors> tag within a "web.config" configuration file located in the root directory of the current web application. This <customErrors> tag should then have its "mode" attribute set to "Off".



<configuration>
    <system.web>
        <customErrors mode="Off"/>
    </system.web>
</configuration>
adding the screenshot here for better  view..
![image](https://user-images.githubusercontent.com/48408687/92099785-9caa7f80-ede3-11ea-9541-2d9c14070cbd.png)

**Comment by true-zanuda** [comment]
I saw that error but it gone when I entered config app url again.

**Comment by v-smahaj** [comment]
@AlanMRichards - Is this issue resolved or are you still facing same issue?
