### ISSUE TITLE
FAQ Plus, ask the expert opened by admin adaptive card

### ISSUE THREAD

**Issue by goksu999** [OfficeDev/microsoft-teams-apps-faqplus#190]
When a question is asked to the expert by the end user, a special card is opened in the admin team. This card is as follows.

<img width="360" alt="Screenshot_6" src="https://user-images.githubusercontent.com/46975324/194534738-92c955c9-4061-4d83-9cbf-d22058a5748b.png">

The problem is, I want to change the content of the "Chat with ..." part of the image and I want the user to be emailed when this button(Chat with button) is pressed. I went through the source code of the application for the solution of this, but I could not reach the result.

Which folder should I look in the source codes to customize this card?

**Comment by gsv022** [comment]
Hi @goksu999 ,
Thanks for raising the query. We understand your requirement and it can be done but we won't be able assist much on this scenario.
