### ISSUE TITLE
How can ı add photo to Faq Plus?

### ISSUE THREAD

**Issue by goksu999** [OfficeDev/microsoft-teams-apps-faqplus#191]
I add photos and test in faq plusa qna maker, it works as in the screenshot.

<img width="267" alt="Screenshot_4" src="https://user-images.githubusercontent.com/46975324/196103998-e2e32d65-bd6f-4fb1-8ceb-e9201294380f.png">

After publishing QnA maker, I can't see the photo in faq plus application. can you help, screenshot is below.

<img width="573" alt="Screenshot_6" src="https://user-images.githubusercontent.com/46975324/196104960-97e2e663-741d-4562-a29d-14ffedd32fc0.png">

**Comment by v-royavinash** [comment]
Hi @goksu999 , Can you please create QnA pairs with images from the expert app instead and check if the images are returned as as part of valid response?

**Comment by goksu999** [comment]
Hi @v-royavinash , As you said I created a QnA from the expert team as follows.

<img width="406" alt="faqqq" src="https://user-images.githubusercontent.com/46975324/196244455-0223141c-6dce-4d89-9940-677681593aba.png">

I am getting an error even though I get the url link of any photo from the images. I am waiting for your help.

Thanks.

**Comment by goksu999** [comment]
By the way, I noticed something, I used the image url you put while reviewing your document. Screenshot is below.

<img width="385" alt="testsetst" src="https://user-images.githubusercontent.com/46975324/196248856-b7e12050-ec56-4c06-8c94-4367588245df.png">
<img width="336" alt="asfadsasf" src="https://user-images.githubusercontent.com/46975324/196248991-a9e3616d-c6a2-40d8-b80e-92e1eedefd21.png">

The url you used in your document is working but any photo url from google is not working, this situation sounded interesting, i was wondering your thoughts.

**Comment by v-royavinash** [comment]
@goksu999 Can you please share the exact URL which is not working for you. If the image URl is valid, ideally it should work. It should be a valid raw image URL.

**Comment by goksu999** [comment]
Of course, I tried 2 different url ways, this is the url I got from the google image I'm going to post ; https://images.app.goo.gl/M57U3s5398fMFQo88

this is an ordinary image url that I got from images;
https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/f8/59/1b/doga-kutlu-apart.jpg?w=700&h=-1&s=1 (with copy link adress)

I made copy link addresses because it should start with https.

**Comment by gsv022** [comment]
Hi @goksu999 ,
Please give us sometime. We will get back to you with proper response soon.

**Comment by v-royavinash** [comment]
@goksu999 , 

- Image 1 :  [https://images.app.goo.gl/M57U3s5398fMFQo88](https://images.app.goo.gl/M57U3s5398fMFQo88) 
                    This is not valid image URL instead its a page URL with image.

- Image 2 : [https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/f8/59/1b/doga-kutlu-apart.jpg?w=700&h=-1&s=1](https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/f8/59/1b/doga-kutlu-apart.jpg?w=700&h=-1&s=1) 
                  Its a valid image URL, however since it doesn't have the valid file extension.

Please use valid image URL with valid file name and it should work. Below is a sample images URL from internet,
[https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png](https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png)

**Comment by goksu999** [comment]
Thank you very much, file extension as I understand it. must end with png. Finally, the extension of most photos in google images does not end with ".png". How can we make .png the extension of the image we selected so that the photo ends with png?

Thank you so much for responding.

**Comment by goksu999** [comment]
Thank you so much,

Have a good day!
