### ISSUE TITLE
I'm getting an error during deployment!!

### ISSUE THREAD

**Issue by goksu999** [OfficeDev/microsoft-teams-apps-faqplus#194]
Hi,

In step2, I am getting an error during the azure deployment phase of the application. I choose qna maker sku as "s0" by default and I get an error. I've never had an error like this before. The output of the error is as follows;

"The subscription does not have QuotaId/Feature required by SKU 'S0' from kind QnAmaker"

How can i solve the problem, thank you.

**Comment by gsv022** [comment]
Hi @goksu999 ,
Thanks for logging the issue.  It won't be possible to deploy FAQ now as QnA Maker itself is retired from Microsoft Azure and you won't be able to create new QnAMaker service. 
A newer version of the [custom question and answering](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-us%2Fproducts%2Fcognitive-services%2Fquestion-answering%2F&data=05%7C01%7Cv-saigattu%40microsoft.com%7Cf147e97f0a7045c5b97d08dac409f52b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638037844321397332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=c1VhmL7QgxuUoJhEUDUgLDeaMGnYMyaYlHB5uKTGQEk%3D&reserved=0) capability is now available as part of Azure Cognitive Service for Language. We are working on creating a new version of FAQ Plus using question answering within the Language Service as part of the upcoming release. As of now the expected date of new release is 29th November.

**Comment by goksu999** [comment]
Hi @gsv022 
Thank you for your answer. As far as I understand, it is impossible to install such an application at the moment. We have to wait for the new version of the question and answer service.(QnA service) Is it true? 
Thanks again,
Best regards.

**Comment by gsv022** [comment]
@goksu999 , 
Yes, as of now the new deployment with QnA service can't be done.

**Comment by goksu999** [comment]
Hi,
Are there any developments about the new QnA service?

**Comment by gsv022** [comment]
Hi @goksu999 ,
Thanks for the patience. Currently the new version is in UAT and waiting for an update on that. As of now, the date of release is not fixed yet. We will keep you posted on this.

**Comment by gsv022** [comment]
@goksu999 , the wait is over. The new version has been released with Azure Cognitive Service for Language. Please let us know if you have any queries related to FAQ Plus.

**Comment by goksu999** [comment]
Thank yo so much @gsv022

**Comment by gsv022** [comment]
Hi @goksu999 ,
We are closing this request as we have provided the inputs for the query raised. If you face any issue with FAQ Plus please raise a new issue for further assistance.
