### ISSUE TITLE
How to change the expert channel

### ISSUE THREAD

**Issue by RiverChen1988** [OfficeDev/microsoft-teams-apps-faqplus#20]
We need to edit the Teams ID in the configuration page and install the expert app to this Team, but the app will send message to General channel, Can we change to another channel, so it won't border all the Teams member

**Comment by AmitKhot2508** [comment]
Hi @RiverChen1988, The Expert App will get installed in the general channel only. This is by design.

**Comment by Dusted1969** [comment]
I've deployed the bot and its all working great - thanks!  I'd also like to use the Bot in a Channel other than General as well - is that on the roadmap?  Its possible to select a channel when installing the app...

![image](https://user-images.githubusercontent.com/45052023/84020250-6ee7a300-a97a-11ea-851e-6cdba0730dfa.png)

**Comment by v-smahaj** [comment]
Thank you for reporting this. For FAQ Plus repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
