### ISSUE TITLE
FAQPlus Experts App Usage Reporting Issue

### ISSUE THREAD

**Issue by EYSue** [OfficeDev/microsoft-teams-apps-faqplus#203]
At EY we are using FAQPlus V1.3
Our Service Adoption team has been having issues with AskMe (FAQplus) expert query extraction for a few months now and we are looking for assistance to resolve.

Every month, we connect to an Azure table to download the query data handled by the expert team. However, the table only provides data until September 2022 and displays an empty table for all other future months.

Is there any known issue with the reporting feature or any advice on how to troubleshoot/resolve?

**Comment by gsv022** [comment]
Hi @EYSue ,
Thanks for raising the query. Please give us sometime and will get back to you with proper response soon.

**Comment by gsv022** [comment]
@EYSue ,could you please respond to the below queries.

- After September if data is not reflecting in the tables which type of data is being inserted into the table
- If it is related to tickets in the tables, we have tested it from our end that after asking a question to the expert, the ticket is getting created in the tickets table. Basically it is working for us.

**Comment by EYSue** [comment]
@gsv022 this is a copy of the data fields that we normally get in this report 
![image](https://user-images.githubusercontent.com/91881396/211771340-5d203c8b-d4e3-4277-a417-56e19d6ac42f.png)
It does relate to tickets but no data has been displayed since September so we need assistance on troubleshooting.

**Comment by gsv022** [comment]
@EYSue, could you please share your outlook id so that we can discuss more on this issue internally.

**Comment by EYSue** [comment]
@gsv022 this is my mail address smcinulty@uk.ey.com

**Comment by gsv022** [comment]
Hi @EYSue ,
We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
