### ISSUE TITLE
Exception: Cannot bind argument to parameter 'botIdValue' because it is null

### ISSUE THREAD

**Issue by magafaterr** [OfficeDev/microsoft-teams-apps-faqplus#206]
Using a fresh download of the solution, when running the deploy.ps1 script, I am getting an error message as shows in the screenshot below.

![MicrosoftTeams-image (25)](https://user-images.githubusercontent.com/31663497/219208306-b1635da6-51ed-4de5-8d14-085ad3249c37.png)

Can you please assist with troubleshooting? @Porkai-Pandian

**Comment by gsv022** [comment]
Hi @magafaterr ,
Thanks for raising the query. Could you please share the deployment logs. Here is the reference.
<img width="760" alt="image" src="https://user-images.githubusercontent.com/98143492/219316366-84ff2c58-457e-49cc-9935-bc6021e887a3.png">
<img width="724" alt="image" src="https://user-images.githubusercontent.com/98143492/219316624-b5e3b45d-5e21-4676-9705-d7f5d4b94a63.png">

**Comment by magafaterr** [comment]
Nothing was created on the tenant, so there isn't one to share unfortunately. It never gets that far....

**Comment by v-royavinash** [comment]
@magafaterr Could you please share your outlook Id?

**Comment by gsv022** [comment]
@magafaterr , Please share the outlook Id.

**Comment by magafaterr** [comment]
Can I share that internally?

**Comment by gsv022** [comment]
Please drop me  a mail  at **v-saigattu@microsoft.com**
