### ISSUE TITLE
Error 501 on Experts Functions

### ISSUE THREAD

**Issue by brunofreitasbr** [OfficeDev/microsoft-teams-apps-faqplus#21]
I'm receiving an error 501 when trying to access the experts functions on the bar or on the Teams Experts group, and an unknow error when sending messages to the bot itself. I can't receive any type of response.

My scenario below: The deployment of the Faq Plus has been made in one Tenant and the application is running on a Teams in another Tenant (Multi-Tenant selection has been selected on App Registration). And on the Configuration Page everything has been inputted correctly.

**Comment by coderkrishna92** [comment]
So when you were deploying the resources, which tenant ID were you using? Did you use the tenant ID of your Teams tenant, or was the tenant ID of your Azure subscription used? I am assuming the latter because what should happen for this to work is that you would need to provide the tenant ID of the Teams tenant here:

![image](https://user-images.githubusercontent.com/62812857/82925520-a2fea500-9f32-11ea-9c7e-4afa27c7e542.png)

**Comment by brunofreitasbr** [comment]
Hello @coderkrishna92, you're right and your solution worked perfectly. But I found another problem when trying to access the Experts bar, on the Recents, Unassigned, Assigned, I'm receiving this: "Unable to reach app. Please try again." with error status 502 "<BotError>Bot returned unsuccessful status code InternalServerError" (errorCode: 1008).

Does you have any information about it? Thanks

**Comment by coderkrishna92** [comment]
A couple of things to check: 
1. Did you properly update the Tenant IDs in the necessary configurations? For the Function App, and the bot? I assume that you did.
2. You may need to give some time to refresh everything, and the data would show up.

**Comment by petecuttriss** [comment]
Hi @coderkrishna92, I'm also seeing the same issue that @brunofreitasbr noted.  I've deployed the solution to a couple of different tenancies now and in both cases everything works as specified except for the Experts bar, on the Recents, Unassigned, Assigned, I'm receiving this: "Unable to reach app. Please try again."   I can reach the Knowledge Base.   I've checked the Tenant ID's in all the various services and they are consistent and match the Teams tenant Id which is the same as the associated Azure tenancy.

Are there any other trouble shooting tips you could recommend?   When you say "Also if you can attach any screenshots from your ApplicationInsights it could help"... which of the three App Insights instances are referring to?  Ref attached images.  Thanks for your time and assistance.

Kind regards
![Unable_to_reach_the_app](https://user-images.githubusercontent.com/4825764/91689716-c7fd5680-ebb8-11ea-807a-807c131d6182.PNG)
![Knowledge_base](https://user-images.githubusercontent.com/4825764/91689725-cc297400-ebb8-11ea-80df-230313351555.PNG)
![AppInsights](https://user-images.githubusercontent.com/4825764/91689750-d9466300-ebb8-11ea-85a8-3b8af652824a.PNG)

**Comment by petecuttriss** [comment]
I've checked the Azure StorageConnectionString and I can see data in the table storage it just isn't being returned for some reason.

**Comment by petecuttriss** [comment]
Hi @brunofreitasbr and @coderkrishna92,  I think I've found the issue in my case.
