### ISSUE TITLE
change the orginal name

### ISSUE THREAD

**Issue by ebeauliere** [OfficeDev/microsoft-teams-apps-faqplus#22]
If I would like to change the orginal name (FAQ Plus) to another name (If doable),  where should I make modifications  and what are the required modifications?

**Comment by AmitKhot2508** [comment]
Hi @ebeauliere, Its doable. You have to do changes in 2 places.
1.  In manifest file under name node.
![image](https://user-images.githubusercontent.com/57248245/83747251-faf98200-a67d-11ea-8f86-d0181934201d.png)

2. In bot service - Go to bot service => search for your bot service if there are many => under Bot management tab => click on settings and there change the display name.
![namechange](https://user-images.githubusercontent.com/57248245/83748263-8c1d2880-a67f-11ea-83ce-01c1c47cbe44.jpg)

**Comment by true-zanuda** [comment]
@ebeauliere , can you close the issue if answer has helped?

**Comment by ebeauliere** [comment]
Thank you!
