### ISSUE TITLE
Track Feedback

### ISSUE THREAD

**Issue by colbytimmsl** [OfficeDev/microsoft-teams-apps-faqplus#24]
Currently the feedback provided by users isn't tracked. Would be great if that information was tracked in the table storage like ticket info, especially when it comes to using the data for analytics (Power BI) purposes.

**Comment by ahmedmahmoudR** [comment]
Is there any solution to this request

**Comment by v-smahaj** [comment]
For FAQ Plus repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
