### ISSUE TITLE
Cannot deploy the solution after select azure region other than the default

### ISSUE THREAD

**Issue by acamina** [OfficeDev/microsoft-teams-apps-faqplus#28]
Hi , when trying to deploy FAQ BOT v2  ( we tried in three different subscriptions ) we are getting this error
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/51921094/86371027-b105bb00-bc80-11ea-9ed2-46648164ec1f.png)
( see attached file ) 

I have attached the deployment details and errors.

    "error": {
      "code": "DeploymentFailed",
      "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
      "details": [
        {
          "code": "Conflict",
          "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
        }
      ]
    },
    "validationLevel": "Template"
  }
}

if i select any other azure region it works ok.

**Comment by nephinj** [comment]
Not working for me with Canada Central as well.

**Comment by true-zanuda** [comment]
I saw a "conflict" status when was trying to use `[Base Resource Name]` which already used by someone else. Maybe it'll helps...

**Comment by v-smahaj** [comment]
This doesn't seem to be issue with Azure Region.
Please scale up App Service plan to S3. Then, go to App Service => Deployment Center => Sync.
Let us know if issue still persists.
