### ISSUE TITLE
Can't Access Bot without Permissions to both End-User and Expert App

### ISSUE THREAD

**Issue by HaleCT2** [OfficeDev/microsoft-teams-apps-faqplus#29]
Bot will only reply when User has permissions for both apps, with the End User Bot installed to their Teams. In this situation, it shows that the Expert Bot is the one actually replying. Are their suggestible changes to the App Manifests to make to avoid this issue? Since both Manifests are pointing to the same Bot Registration, is this easily avoidable? 

<img width="805" alt="Screen Shot 2020-07-06 at 7 58 34 AM" src="https://user-images.githubusercontent.com/44034905/86590919-89ec0980-bf5e-11ea-8902-7e6bc9403c35.png">

Thank you.

**Comment by v-smahaj** [comment]
For FAQ repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
