### ISSUE TITLE
Bot not working when setting AlwaysOn to false...

### ISSUE THREAD

**Issue by gdover-twu** [OfficeDev/microsoft-teams-apps-faqplus#30]
I've set AlwaysOn to False so that I could downgrade AppService plan to save costs... Does this compromise functionality? Sorry if this is a dumb question/non-issue.

Thank you!

**Comment by MichaelLaMontagne** [comment]
Seeing the same issue. Went with a B1 Dev/Test SKU. Not sure why it breaks with this template, I have other bots using QnA that work with F1.

**Comment by westerdaled** [comment]
I get the warning when I tried to move from S1 plan to one of the targetted compute plans such as the one you meention  I think this a major issue as the bot is quite expensive even when it is not in use.

**Comment by abbodh** [comment]
Although it is recommended to use Standard tiers during deployment in order to allow the QnA maker, bot service, configuration app service and azure functions to leverage the app service resources. You can later reduce the SKUs if the traffic is not high. 

@MichaelLaMontagne could you please help to share the error when switched to lower SKUs?

**Comment by MichaelLaMontagne** [comment]
![image](https://user-images.githubusercontent.com/37764843/89602775-b7a9c400-d824-11ea-95a4-9cd051198ab8.png)

**Comment by MichaelLaMontagne** [comment]
If you disable AlwaysON to change the SKU the bot doesn't respond. I have no issues with other bots and QnA without that feature.

**Comment by v-smahaj** [comment]
Setting AlwaysOn to False won't compromise any functionality.
It will just increase response time of the app service. Please read this FAQ https://docs.microsoft.com/en-us/azure/app-service/faq-availability-performance-application-issues#how-do-i-decrease-the-response-time-for-the-first-request-after-idle-time
