### ISSUE TITLE
Please help! Need extra help: Step 5 from Deployment Guide

### ISSUE THREAD

**Issue by jjbol123** [OfficeDev/microsoft-teams-apps-faqplus#35]
Good day, who can help me? I have gone through all the steps from the deployment guide to step 5.1: "Finish configuring the FAQ Plus [Version 2] app". Only when I log in to https://contosofaqplus1-config.azurewebsites.net with preset login details, I get this error : "This user does not have the proper permissions for this action. Please sign in with a valid user credentials." What could be wrong? I have followed exactly all the steps from the tutorial. Also the login details are correct. Please help! I would like to continue with step 5.2 from the deployment guide. :-) I have admin rights in Azure.

**Comment by shanemeisner** [comment]
Currently having the exact issue.. I can access everything in Azure with the account I created it with. But get the "This user does not have the proper permissions for this action. Please sign in with a valid user credentials." message as well.

**Comment by jjbol123** [comment]
> 
> 
> Currently having the exact issue.. I can access everything in Azure with the account I created it with. But get the "This user does not have the proper permissions for this action. Please sign in with a valid user credentials." message as well.

Dear Scheine Meisner, thank you for letting me know that you have the same problem. What is the best thing to do to get it resolved by Microsoft?

**Comment by shanemeisner** [comment]
OK, so I found out my issue.. 
When configuring the "Config Admin UPN List" I had entered my email address. 
But here we use our employee ID to log into the environment, not our email address. 
Once I updated the Admin list with my employee ID I was able to get to the Configuration.
Hope this helps others.

**Comment by jjbol123** [comment]
> OK, so I found out my issue.. 
> 
> When configuring the "Config Admin UPN List" I had entered my email address. 
> 
> But here we use our employee ID to log into the environment, not our email address. 
> 
> Once I updated the Admin list with my employee ID I was able to get to the Configuration.
> 
> Hope this helps others.


Dear Sheine Meisner, thanks for the help and the thinking along with me. Hopefully this solution will work for me too, because I don't have any employee ID’s.  Only my own emailadress. Monday I will try the solution.  Have a nice weekend.

**Comment by jjbol123** [comment]
> 
> 
> OK, so I found out my issue..
> When configuring the "Config Admin UPN List" I had entered my email address.
> But here we use our employee ID to log into the environment, not our email address.
> Once I updated the Admin list with my employee ID I was able to get to the Configuration.
> Hope this helps others.

Dear Shane Meisner, on your sentence: "_Once I updated the Admin list with my employee ID I was able to get to the Configuration._", I have a question: Where can I update the admin list?

**Comment by shanemeisner** [comment]
here is how I Got there.. 
Went to Azure Portal ( https://portal.azure.com/) selected Resource Groups and selected the resource I added the Bot to. Then selected "Deployments" and selected "Microsoft.Template". 
Selected Inputs and updated "configAdminUPNList". 
Add the login name needed to authenticate to the environment. In our case we use our Employee ID.
Back to the Overview and select redeploy.

**Comment by jjbol123** [comment]
> here is how I Got there.. 
> 
> Went to Azure Portal ( https://portal.azure.com/) selected Resource Groups and selected the resource I added the Bot to. Then selected "Deployments" and selected "Microsoft.Template". 
> 
> Selected Inputs and updated "configAdminUPNList". 
> 
> Add the login name needed to authenticate to the environment. In our case we use our Employee ID.
> 
> Back to the Overview and select redeploy.


I found it.  But it is only read-only.  No editing mode. :-(

**Comment by jjbol123** [comment]
> here is how I Got there.. 
> 
> Went to Azure Portal ( https://portal.azure.com/) selected Resource Groups and selected the resource I added the Bot to. Then selected "Deployments" and selected "Microsoft.Template". 
> 
> Selected Inputs and updated "configAdminUPNList". 
> 
> Add the login name needed to authenticate to the environment. In our case we use our Employee ID.
> 
> Back to the Overview and select redeploy.


unfortunately this was not a solution for me.  I only use my email address that I use to log into the Azure portal.  I also provided this email address in one of the steps in the tutorial. But still I don't have access :-(

**Comment by westerdaled** [comment]
@shanemeisner 

I too have the same issue. 
![The users does not have the proper permissions for this action](https://user-images.githubusercontent.com/937208/87985745-0260d780-cad4-11ea-84db-0e23ab9e1ce9.PNG)


 I have tried  both my GA MFA account and a non MFA account - these are the ones listed in <kbd>configAdminUPNList</kbd> 

I will try and do a bit of googling in the morning to see if there is anything obvious.

**Comment by westerdaled** [comment]
@jjbol123 

I have fixed my issue which was due to having a comma separating the two names in the admin UPN list.

All you need to do is hit the redeploy button in the  Microsoft Template Overview page THis takes you back to the deploy dialog screen which displays your original values (accept the app secret) .  Hence, I edited the UPN admin list and entered my app secret. Hit the purchase button. Thereafter, when I sign in I get the config page as seen in the deployment instructions.

**Comment by jjbol123** [comment]
> 
> 
> @jjbol123
> 
> I have fixed my issue which was due to having a comma separating the two names in the admin UPN list.
> 
> All you need to do is hit the redeploy button in the Microsoft Template Overview page THis takes you back to the deploy dialog screen which displays your original values (accept the app secret) . Hence, I edited the UPN admin list, replacing the comma with a semicolon, and added my app secret. To deploy, hit the the purchase button. Thereafter, when I sign in I get the config page as seen in the deployment instructions.

@westerdaled @shanemeisner @abbodh  : Thank you for your help, I really appreciate that. I looked again in the 'configupnlist' and there is the email address that I use to log in to the Azure Portal and in the configuration app. Still, I keep seeing the screen below. What is going on?

![afbeelding](https://user-images.githubusercontent.com/53079899/88169022-9f7a5800-cc1b-11ea-875c-0f823a0288e4.png)

**Comment by westerdaled** [comment]
@jjbol123 

I would follow my steps so you can copy and paste the UPN into a new login screen ( this will check for any hard to spot typos) .  Also,  review steps 3 including  the urls  & check "Implicit grant", check "Access tokens" and "ID tokens".
In your case all your URls start with:  https://msfaqplus11-config.azurewebsites.net . I used a similar  equivalent url  to login.

**Comment by jjbol123** [comment]
@westerdaled 
I have checked and followed all the steps you have specified, but I keep the same screen.

**Comment by shanemeisner** [comment]
@jjbol123  at this point I'd recommend going back to the main site: https://github.com/OfficeDev/microsoft-teams-apps-faqplus and try contacting some of the contributors there. I noticed that ktcodebite  updated the readme file recently so maybe start with him.
Good luck!!

**Comment by jjbol123** [comment]
@ktcodebite : Can you help me? I have done all steps up to step 5.1 from the Deployment Guide. However, I do not see the same screen in step 5.2 from the Deployment guide, but I see the screen below. What is not going well? 
![afbeelding](https://user-images.githubusercontent.com/53079899/88182014-effbb080-cc2f-11ea-9af8-1a57163d9733.png)

**Comment by jjbol123** [comment]
> 
> 
> @jjbol123 at this point I'd recommend going back to the main site: https://github.com/OfficeDev/microsoft-teams-apps-faqplus and try contacting some of the contributors there. I noticed that ktcodebite updated the readme file recently so maybe start with him.
> Good luck!!

Thank you.

**Comment by vinayakrathore** [comment]
Facing same issue...
![image](https://user-images.githubusercontent.com/58435962/88283667-7f28c700-cd09-11ea-9b5a-4e2fa4a8b11b.png)

**Comment by jjbol123** [comment]
> 
> 
> @jjbol123 at this point I'd recommend going back to the main site: https://github.com/OfficeDev/microsoft-teams-apps-faqplus and try contacting some of the contributors there. I noticed that ktcodebite updated the readme file recently so maybe start with him.
> Good luck!!

@shanemeisner : I couldn't find any information in the readme file that could indicate a solution. Why aren't other users bothered by the problem and can they access the configuration app? I asked ktcodebite for help.

**Comment by vishnuabhrapudi** [comment]
Hi @jjbol123, it looks like the configuration URL is incorrect, it should be "https://[BaseResourceName]-config.azurewebsites.net/".

We have made the changes in Deployment Guide for same.

**Comment by jjbol123** [comment]
> 
> 
> Hi @jjbol123, it looks like the configuration URL is incorrect, it should be "https://[BaseResourceName]-config.azurewebsites.net/".
> 
> We have made the changes in Deployment Guide for same.

@vishnuabhrapudi : Thank you very much for your response. I have made some changes, but I still have the same problem. What is going on? I am a global administrator in Azure.

![afbeelding](https://user-images.githubusercontent.com/53079899/89173013-e0f7f500-d583-11ea-8197-2d07f595fb6c.png)

**Comment by jjbol123** [comment]
> 
> 
> Hi @jjbol123, it looks like the configuration URL is incorrect, it should be "https://[BaseResourceName]-config.azurewebsites.net/".
> 
> We have made the changes in Deployment Guide for same.

@vishnuabhrapudi : I have gone through all the steps in the Deployment Guide (https://github.com/OfficeDev/microsoft-teams-apps-faqplus/wiki/Deployment-Guide) again, but still have the same problem in step 5.1 (finish configuring the FAQ Plus app). When I use https://msfaqplus13-config.azurewebsites.net and log in, I see the screen below again:
![afbeelding](https://user-images.githubusercontent.com/53079899/89188626-35f53480-d59f-11ea-8966-d5e08898167d.png)

Can you tell me how I get to see the screen in step 5.2 from te Deployment Guide?
![afbeelding](https://user-images.githubusercontent.com/53079899/89188807-705ed180-d59f-11ea-9361-cfad1b0c56b2.png)

**Comment by westerdaled** [comment]
Today I deleted all my V2 resource, since upgrading seems impossible ( and accidently deleted my knowledge base linked to QnA service) 😢 . Next I went through the deployment steps up to the screen above ( https://[mybaseresouce]-config.azurewebsites.net/.  When I login with the my MFA global admin account I am presented with a consent screen, then you get the screen you are trying to get to.  Provided you have the correct tenant admin permissions  and ensure you checked ID tokens only in the Authentication -> Implicit Grant  ( they seemed to have dropped access token), this should work.   Note the config App has the default API Permissions ->  User.Read Graph permissions

**Comment by vishnuabhrapudi** [comment]
> > Hi @jjbol123, it looks like the configuration URL is incorrect, it should be "https://[BaseResourceName]-config.azurewebsites.net/".
> > We have made the changes in Deployment Guide for same.
> 
> @vishnuabhrapudi : I have gone through all the steps in the Deployment Guide (https://github.com/OfficeDev/microsoft-teams-apps-faqplus/wiki/Deployment-Guide) again, but still have the same problem in step 5.1 (finish configuring the FAQ Plus app). When I use https://msfaqplus13-config.azurewebsites.net and log in, I see the screen below again:
> ![afbeelding](https://user-images.githubusercontent.com/53079899/89188626-35f53480-d59f-11ea-8966-d5e08898167d.png)
> 
> Can you tell me how I get to see the screen in step 5.2 from te Deployment Guide?
> ![afbeelding](https://user-images.githubusercontent.com/53079899/89188807-705ed180-d59f-11ea-9361-cfad1b0c56b2.png)


Hi @jjbol123, Can you please follow the below steps and validate if everything is in place?

1. Goto Config App Service and click on Configuration on left menu
![image](https://user-images.githubusercontent.com/58915530/89289612-28aa7980-d675-11ea-8da8-ea0bf81a06a3.png)
2. Click on ValidUpns setting and confirm whether the email with which you are trying to login to Configuration app is entered here.

**Comment by jjbol123** [comment]
> 
> 
> > > Hi @jjbol123, it looks like the configuration URL is incorrect, it should be "https://[BaseResourceName]-config.azurewebsites.net/".
> > > We have made the changes in Deployment Guide for same.
> > 
> > 
> > @vishnuabhrapudi : I have gone through all the steps in the Deployment Guide (https://github.com/OfficeDev/microsoft-teams-apps-faqplus/wiki/Deployment-Guide) again, but still have the same problem in step 5.1 (finish configuring the FAQ Plus app). When I use https://msfaqplus13-config.azurewebsites.net and log in, I see the screen below again:
> > ![afbeelding](https://user-images.githubusercontent.com/53079899/89188626-35f53480-d59f-11ea-8966-d5e08898167d.png)
> > Can you tell me how I get to see the screen in step 5.2 from te Deployment Guide?
> > ![afbeelding](https://user-images.githubusercontent.com/53079899/89188807-705ed180-d59f-11ea-9361-cfad1b0c56b2.png)
> 
> Hi @jjbol123, Can you please follow the below steps and validate if everything is in place?
> 
>     1. Goto Config App Service and click on Configuration on left menu
>        ![image](https://user-images.githubusercontent.com/58915530/89289612-28aa7980-d675-11ea-8da8-ea0bf81a06a3.png)
> 
>     2. Click on ValidUpns setting and confirm whether the email with which you are trying to login to Configuration app is entered here.

@vishnuabhrapudi : Here you will find the email address I used in step 2.7 of the Deployment Guide.

**Comment by jjbol123** [comment]
Today I will go through all the steps in the Deployment Guide again. In Azure I have the role of Global Administrator. Hopefully this time I can manage to get the screen at step 5.2. I'll keep you informed.

**Comment by westerdaled** [comment]
@jjbol123 

I suspect it is the account that you using  - remember it doesn't have to be an admin account to be deemed an expert .
My last bit of advice would be to go to 

Your resource group , click on templates then click on Microsoft Template. 
here you can inspect your inputs inc the UPN e.g. user@mytenant.onmicrosoft.com . I you hit redeploy you get the original form for you to change the user or add another ( comma separated) . 


![Resource deployments](https://user-images.githubusercontent.com/937208/89417443-995d9e80-d726-11ea-9578-6e2cfc4fe652.png)

**Comment by jjbol123** [comment]
> UPN
@westerdaled :
Good morning Daniel, thank you again for your help. I really appreciate that.

I checked again in the settings in Azure following your comments.

I even created a second email address (comma seperated) at UPN after adding that extramail address to the Azure Active Directory and granting access rights via Enterprise Applications.

But this also did not help.

I further understand from your story that I do not necessarily have to be an administrator in Azure to access the Config App. Did I understand that correctly?

Have you made further progress in your research into the costs of the Microsoft Faq Plus app?

**Comment by abbodh** [comment]
@jjbol123 - were you able to solve the login issue in configuration app? If not, can you please confirm that the config admin UPN provided during ARM deployment belongs to same tenant where of your azure subscription? Please note that the unlike bot application registration, the configuration app is set to support single tenant only and only allow users of the tenant provided during ARM deployment to access the app. 

Also, can you please try to share the application insight error logs to know more about sign in failure?

**Comment by jjbol123** [comment]
> 
> 
> @jjbol123 - were you able to solve the login issue in configuration app? If not, can you please confirm that the config admin UPN provided during ARM deployment belongs to same tenant where of your azure subscription? Please note that the unlike bot application registration, the configuration app is set to support single tenant only and only allow users of the tenant provided during ARM deployment to access the app.
> 
> Also, can you please try to share the application insight error logs to know more about sign in failure?

@abbodh : Dear Abhijeet Bodhankar, thank you for thinking along with me and informing me how the app is doing.

This Monday, August 10, I have time again to look at the Microsoft Faq Plus App and send you the requested information. Is that OK? Have a nice day and thank you again.

**Comment by v-smahaj** [comment]
Let us know if issue still persists.
