### ISSUE TITLE
Upgrade steps from V2 to V3

### ISSUE THREAD

**Issue by westerdaled** [OfficeDev/microsoft-teams-apps-faqplus#39]
@abbodh looks like I deployed V2 , so now I need to go through the upgrade steps to V3. Am I am able to update FAQPlus Bot service remotely and then redeploy?

Today I freshly cloned the repo and I notice the sample manifests still refer to V2
```
`
  },
  "name": {
    "short": "FAQ Plus [V2]"
  },

`

```

**Comment by westerdaled** [comment]
@abbodh  looks like you are already on this: [https://github.com/OfficeDev/microsoft-teams-apps-faqplus/commit/6f99a662a89bd2e22ce4672c71045d69540f6417](https://github.com/OfficeDev/microsoft-teams-apps-faqplus/commit/6f99a662a89bd2e22ce4672c71045d69540f6417).  I am happy to test out the upgrade steps for getting this to work.

**Comment by shanemeisner** [comment]
I've been searching for the last day or so for "Upgrade Steps" and not finding any.. So hopefully someone responds here as what they add to V3 looks promising.

**Comment by westerdaled** [comment]
@shanemeisner 

Yes, not being able to upgrade to V3 is frustrating.  The current branch has the multi-turn response  support which they have given a tag: 171663. So it could be a case of hitting the redeploy button and reloading the manifests, albeit with a correct <code>"short"</code> value.

**Comment by abbodh** [comment]
Hi @westerdaled 

thanks for sharing the feedback around manifest file still referring the name as v2. Although there are no changes in terms scope and capabilities in Teams manifest package, so you can still refer the existing deployed package. 

@shanemeisner can you please refer the continuous deployment page https://github.com/OfficeDev/microsoft-teams-apps-faqplus/wiki/Continuous-Deployment#continuous-deployment-in-azure-app-services to upgrade the build to refer latest code changes. 

The July 2020 (version 3) release of FAQ Plus includes a multi-turn feature to the end user experience. With the multi-turn feature, users will be presented with follow-up options along with an answer to their question. This enables the FAQ Plus bot to answer the user's question with more relevance. Multi-turn follow-up options are programmed directly into the QnA Maker when the tenant admin uploads the Q&A pairs into the knowledge base.

**Comment by shanemeisner** [comment]
Thanks for the information!

**Comment by westerdaled** [comment]
@shanemeisner @abbodh 

Yes, thanks. I am not sure if the git repo is 'locked' but when I click my Azure App Service -> Deployment Center, I get the the progress ( three dots) waiting state 😒. Will try again a bit later.

**Comment by westerdaled** [comment]
@abbodh I've had a few issues with the upgrade 
Firstly, my free test subscription got disabled which I gather is normal when there is no available credit.  I have now upgraded.
Next, did the sync but after testing I realised the app services still points to the old repo. 

![image](https://user-images.githubusercontent.com/937208/88845039-7a698480-d1db-11ea-897b-23d4b16cf586.png)

I have now click disconnect but wish I hadn't! is there any advice on reconnecting the correct repo

**Comment by vishnuabhrapudi** [comment]
Hi @westerdaled,  it looks like the default github url in the deployment guide was pointing old codebase.

We have made the changes in Deployment Guide for same.

**Comment by westerdaled** [comment]
@vishnuabhrapudi 

Thanks I have now set the deployment both both repos, restarted the app service and test the app services url https://mybot.azurewebsites.net

the old repo:
[https://github.com/OfficeDev/microsoft-teams-faqplusplus-app](https://github.com/OfficeDev/microsoft-teams-faqplusplus-app)
Result: service and bot works fine

the new repo:
[https://github.com/OfficeDev/microsoft-teams-apps-faqplus](https://github.com/OfficeDev/microsoft-teams-apps-faqplus)
Result: 
An error occurred while starting the application.
.NET Core 4.6.29017.01 X86 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 2.1.1-rtm-30846    |    Microsoft Windows 10.0.14393    |   Need help?

**Comment by vishnuabhrapudi** [comment]
Hi @westerdaled, can you please verify if "QnAMakerSubscriptionKey" key avaialable in the App service configuration settings? If not there, please add the key to App settings and value as shown in below screenshot
![image](https://user-images.githubusercontent.com/58915530/88856093-87a16600-d211-11ea-814e-26e25e609f25.png)

**Comment by westerdaled** [comment]
@hi @vishnuabhrapudi 

QnAMakerSubscriptionKey is not there.  Unfortunately the image you have posted, isn't rendering ( proxy error) . can you paste the key in text

**Comment by westerdaled** [comment]
@vishnuabhrapudi  

Ok figured why I couldn't see your image ( my VPN) . I have replicated what you have done and used my previously generated key 1 + deployment slot.  Saved<code> QnAMakerSubscriptionKey</code> and still the same runtime issue.  Will pick this up again in the morning.

**Comment by westerdaled** [comment]
@vishnuabhrapudi , do you me to any  regenerate any of the  keys and and set either to <code> QnAMakerSubscriptionKey</code>?

**Comment by vishnuabhrapudi** [comment]
Hi @westerdaled, You can include the subscription key of the QnA service which was created as part of deployment. To understand more about the issue, can you please add "ASPNETCORE_DETAILEDERRORS = true" in app settings and share us the error screenshot.

**Comment by westerdaled** [comment]
@vishnuabhrapudi hope you are well . Is there anything else you want me to implement or configure in order to resolve this issue.  I would prefer to upgrade rather then delete and reinstall.

**Comment by westerdaled** [comment]
I now have a fully working FAQPlus V3 Bot but only by deleting all V2 resources and not going through the upgrade. I am happy to try upgrading from to V4 when this arrives from day a dev branch but only if the changes to the configs are documented.

**Comment by abbodh** [comment]
Thanks for the feedback. We will work on updating the documentation further for ease on upgrading the apps without need of actual delete. 

I am closing the issue now, but please feel free to open a new one if you need further clarifications or facing any deployment challenges.
