### ISSUE TITLE
Not able to complete STEP 5 / Finish configuring the FAQ Plus app

### ISSUE THREAD

**Issue by wsantia2** [OfficeDev/microsoft-teams-apps-faqplus#40]
For the step : Go to the configuration app, which is at https://[BaseResourceName].azurewebsites.net/configuration. When using the configured "BaseResourceName" as per the URL above it send message the URL not found. I am able to access the URL https://[BaseResourceName].azurewebsites.net ( with my defined BaseResourceName") but not when I add configuration at the end. Step 1 to Step 4 have been completed successfully.

Using attached instructions.
https://github.com/OfficeDev/microsoft-teams-apps-faqplus/wiki/Deployment-Guide
 

Any advise here.

Thanks in advance
[Image 1.pdf](https://github.com/OfficeDev/microsoft-teams-apps-faqplus/files/4967844/Image.1.pdf)
[Image 2.pdf](https://github.com/OfficeDev/microsoft-teams-apps-faqplus/files/4967845/Image.2.pdf)

**Comment by vishnuabhrapudi** [comment]
Hi @wsantia2, it looks like the configuration URL is incorrect, it should be "https://[BaseResourceName]-config.azurewebsites.net/".

We have made the changes in Deployment Guide for same.

**Comment by abbodh** [comment]
Resolving the issue as the configuration URL is fixed now.
