### ISSUE TITLE
Link to the deployment template in the deployment guide seems to be wrong

### ISSUE THREAD

**Issue by sandrokahn** [OfficeDev/microsoft-teams-apps-faqplus#42]
The link to the deployment template in the deployment guide seems to be wrong. It points to: https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FOfficeDev%2Fmicrosoft-teams-faqplusplus-app%2Fmaster%2FDeployment%2Fazuredeploy.json 
This is the same location as the deployment script from the [depreciated version](https://github.com/OfficeDev/microsoft-teams-faqplusplus-app/wiki/Deployment-guide)

It also seems that it wants to load the git of the deprecated version (see screenshot).
![image](https://user-images.githubusercontent.com/68634575/88643915-9a595500-d0c2-11ea-9a8f-b4c921ab0c92.png)

**Comment by vishnuabhrapudi** [comment]
Hi @sandrokahn, it looks like there was error in the hyperlink.

We have made the changes in Deployment Guide for same.

**Comment by abbodh** [comment]
Resolving the issue after fixing the Git repo URL link.
