### ISSUE TITLE
Can't get past Step 5 in the setup guide

### ISSUE THREAD

**Issue by chrismoseley** [OfficeDev/microsoft-teams-apps-faqplus#43]
Followed every step in the guide but https://[BaseResourceName].azurewebsites.net/configuration just leads to a 404. As does
https://[BaseResourceName].azurewebsites.net/signin

**Comment by abbodh** [comment]
Hi @chrismoseley , it looks like the configuration URL is incorrect, it should be "https://[BaseResourceName]-config.azurewebsites.net/". 

We have made the changes in Deployment Guide for same.
