### ISSUE TITLE
Stuck on Step 5 - Config URL will display expected form

### ISSUE THREAD

**Issue by Sephiroth0327** [OfficeDev/microsoft-teams-apps-faqplus#44]
I have followed all steps carefully and have created my service in Azure and also created my Knowledge Base.  When I get to Step 5 and navigate to https://botname-config.azurewebsites.net/ I get the screen below.  It does not prompt me to authenticate and does not show the form that I need to fill out.  I did not receive any errors during any of the previous steps.  Other observations:

- When I test the KB from within https://www.qnamaker.ai/, it works as expected
- When I access the Web App Bot in Azure and click "Test in Web Chat", it does not work.  No messages are returned when I type in trigger phrases
- When I navigate to https://botname.azurewebsites.net/, I get the 2nd screenshot below.  I do not understand what I am missing.  I do not think I am supposed to be manually configuring anything though the pages I am seeing are showing that some configuration is missing
- Bot Client ID, Bot Client Secret, Config App Client ID, Tenant ID are all confirmed correct (no extra spaces/characters) - these were entered in Step 2

![image](https://user-images.githubusercontent.com/69170603/89226184-8e313400-d5a9-11ea-8a43-e73dd9b48b1d.png)

![image](https://user-images.githubusercontent.com/69170603/89226558-25968700-d5aa-11ea-8a03-365543c688e7.png)

**Comment by vishnuabhrapudi** [comment]
Hi @Sephiroth0327, Can you please follow below steps and try again.

1. Goto Configuration App Service in Azure portal. Select the Deployment center on the left menu.
![image](https://user-images.githubusercontent.com/58915530/89290172-141ab100-d676-11ea-9749-51de60d47d1a.png)
2. Click on Sync and let the deployment complete. Try again to open the config app. Use the email specified in ValidUpns app setting to log in to config app.

**Comment by Sephiroth0327** [comment]
@vishnuabhrapudi - Thank you for the quick response.  Here is what I see after clicking Sync:

![image](https://user-images.githubusercontent.com/69170603/89297994-b9139a80-d632-11ea-9245-58072629a2a0.png)

Error message detail:

`Command: deploy.cmd
Handling .NET Web Application deployment.
Using Msbuild from 'D:\Program Files (x86)\MSBuild-15.9.21.664\MSBuild\MSBuild\15.0\Bin'.
All packages listed in packages.config are already installed.
Committing restore...
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.Common\obj\project.assets.json
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.AzureFunction\obj\project.assets.json
Restore completed in 384.27 ms for D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.Common\Microsoft.Teams.Apps.FAQPlusPlus.Common.csproj.
Restore completed in 385.3 ms for D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.AzureFunction\Microsoft.Teams.Apps.FAQPlusPlus.AzureFunction.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus\obj\project.assets.json
Restore completed in 379.35 ms for D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus\Microsoft.Teams.Apps.FAQPlusPlus.csproj.

NuGet Config files used:
    C:\DWASFiles\Sites\#1asksamincyte-config\AppData\NuGet\NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
  
  Restore operation started...
libman.json : error LIB002: The "bootstrap@3.4.1" library could not be resolved by the "unpkg" provider [D:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Microsoft.Teams.Apps.FaqPlusPlus.Configuration.csproj]
  
  One or more libraries failed to restore
  
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild-15.9.21.664\MSBuild\MSBuild\15.0\Bin\MSBuild.exe" "D:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Microsoft.Teams.Apps.FaqPlusPlus.Configuration.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\8d8387792658b0e";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="D:\home\site\repository\Source\\"
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\88.20703.4676\bin\Scripts\starter.cmd deploy.cmd`

**Comment by Sephiroth0327** [comment]
@vishnuabhrapudi - I'm not sure what changed but I tried to Resync again tonight.  This time it finally succeeded and I can now access the Config page.  Thanks for your help!  You can close this.
