### ISSUE TITLE
no response from bot(test in web chat ) though have completed all step successfuly

### ISSUE THREAD

**Issue by sargamtiwari** [OfficeDev/microsoft-teams-apps-faqplus#45]
-I have checked and tested  my knowledgebase is working fine on https://www.qnamaker.ai
- I have completed successfully step `5` and all other step also.
- have sync the configuration app service also and it deployed successfully again ,I have checked the log

Command: deploy.cmd
Handling .NET Web Application deployment.
Using Msbuild from 'D:\Program Files (x86)\MSBuild-15.9.21.664\MSBuild\MSBuild\15.0\Bin'.
All packages listed in packages.config are already installed.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.Common\obj\project.assets.json
Restore completed in 369.77 ms for D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.Common\Microsoft.Teams.Apps.FAQPlusPlus.Common.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.AzureFunction\obj\project.assets.json
Restore completed in 424.7 ms for D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.AzureFunction\Microsoft.Teams.Apps.FAQPlusPlus.AzureFunction.csproj.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus\obj\project.assets.json
Restore completed in 362.21 ms for D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus\Microsoft.Teams.Apps.FAQPlusPlus.csproj.

NuGet Config files used:
    C:\DWASFiles\Sites\#1rbeibot-config\AppData\NuGet\NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
  
  Restore operation started...
  Restoring library jquery@3.4.1...
  Restoring library modernizr@2.8.3...
  Restoring library bootstrap@3.4.1...
  Restoring library jquery-validation-unobtrusive@3.2.11...
  Restoring library jquery-validate@1.19.1...
  Restoring library jquery-ajax-unobtrusive@3.2.6...
  
  6 libraries restored in 5.62 seconds
  
CSC : warning SA0001: XML comment analysis is disabled due to project configuration [D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.Common\Microsoft.Teams.Apps.FAQPlusPlus.Common.csproj]
  Microsoft.Teams.Apps.FAQPlusPlus.Common -> D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.Common\bin\Release\netstandard2.0\Microsoft.Teams.Apps.FAQPlusPlus.Common.dll
CSC : warning SA0001: XML comment analysis is disabled due to project configuration [D:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Microsoft.Teams.Apps.FaqPlusPlus.Configuration.csproj]
  Microsoft.Teams.Apps.FaqPlusPlus.Configuration -> D:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\bin\Microsoft.Teams.Apps.FAQPlusPlus.Configuration.dll
  Microsoft.ApplicationInsights.Web: Copying ApplicationInsights.config to bin\
  Transformed Web.config using D:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Web.Release.config into obj\Release\TransformWebConfig\transformed\Web.config.
  Copying all files to temporary location below for package/publish:
  D:\local\Temp\8d838fc27d9210e.
Creating app_offline.htm
KuduSync.NET from: 'D:\local\Temp\8d838fc27d9210e' to: 'D:\home\site\wwwroot'
Copying file: 'bin\Microsoft.Teams.Apps.FAQPlusPlus.Common.dll'
Copying file: 'bin\Microsoft.Teams.Apps.FAQPlusPlus.Common.pdb'
Copying file: 'bin\Microsoft.Teams.Apps.FAQPlusPlus.Configuration.dll'
Copying file: 'bin\Microsoft.Teams.Apps.FAQPlusPlus.Configuration.pdb'
Deleting app_offline.htm
Finished successfully.

-But while testing my bot in web chat I am not getting any response .

-When I open https://mybotname.azurewebsites.net/   it says your bot is ready.
-Even my  messaging endpoint is not up.as it is giving
HTTP 404 error
That’s odd... Microsoft Edge can’t find this page

**Comment by abbodh** [comment]
Hi @sargamtiwari - can you please try to create the Teams application package https://github.com/OfficeDev/microsoft-teams-apps-faqplus/wiki/Deployment-Guide#step-6-create-the-teams-app-packages .

The  https://mybotname.azurewebsites.net/  is not supposed to render anything, as the app uses /api/messages endpoint to serve the incoming bot command requests. 

Please let us know if the bot after installation in Teams worked for you or not.

**Comment by sargamtiwari** [comment]
Hi abbodh,
Thanx for your reply,
I have followed step 6 and created the teams package and deployed to teams  but still not getting any reply

**Comment by v-smahaj** [comment]
Thank you for reporting this. Seems like there would be some deployment issue. Please validate tenant Id in App Service configuration in Azure portal. It should be tenant Id of tenant where manifest is installed.
Please review other configuration values and manifest values as well.
If issue still persists, try scaling up App Service plan to S3 and sync App Service from Deployment Center in Azure portal.
