### ISSUE TITLE
Bot does not respond in Azure>Bot>Test in Web Chat

### ISSUE THREAD

**Issue by Sephiroth0327** [OfficeDev/microsoft-teams-apps-faqplus#47]
I have followed all deployment steps and have also created my QnA KB.  When I access the Config page via https://mybotname-config.azurewebsites.net, the Config page loads and I have input my Teams ID, KB ID and messages.  KB is published and the publish screen confirms the proper name of the QnA Service.

However, when I go to Azure and navigate to the Web Bot and click Test in Web Chat, the bot does not respond at all.  I have redone the steps multiple times and no matter what, the bot never responds.  It works find directly on the QnA site but not within the bot.  I have confirmed that the KB ID is correct.  What can I check to get this resolved?

A few observations:

- If I navigate to Config page, it loads without issue
- If I navigate to https://mybotname.azurewebsites.net, I get the message that the bot is "Ready!" (see https://asksamincyte.azurewebsites.net/)
- If I navigate to https://mybotname-qnamaker.azurewebsites.net, the message says my App Service is up and running but nothing more

Also I noticed that one of the pre-reqs was to have a local copy of the code downloaded but none of the steps prompt me to do anything with that code.  Is a step missing or am I misreading it?  

![image](https://user-images.githubusercontent.com/69170603/89483523-4b6a8a00-d76a-11ea-8304-7a1fa47b7b97.png)

![image](https://user-images.githubusercontent.com/69170603/89483556-5a513c80-d76a-11ea-9336-e2ae7a2a8dab.png)

**Comment by abbodh** [comment]
Hi @Sephiroth0327 - the bot is designed to support msteamschannel (Microsoft Teams). Can you please create the Teams package and try to run the bot in Teams rather than web chat.

**Comment by Sephiroth0327** [comment]
Thank you!

**Comment by bungleweed** [comment]
Hi, what if a customer wants to use the same bot in both Teams a pinned app and also publish it on an existing webpage e.g. IT Self Service or SharePoint Intranet webpage. Can it not support multiple channels?
