### ISSUE TITLE
Can you integrate/expose the FAQ Plus Bot with SharePoint Online?

### ISSUE THREAD

**Issue by petecuttriss** [OfficeDev/microsoft-teams-apps-faqplus#48]
The FAQ Plus bot is fantastic and is working really well within Microsoft Teams.

We are currently looking to see if the same functionality could be exposed from within SharePoint, possibly using an SPFx web part or simply code embed technique (such as this: https://sharepointlessons.wordpress.com/2018/05/15/integrating-faq-bots-with-sharepoint/).

If I try and test the bot using the 'Test in Web Chat' feature within the Azure Portal I don't receive any response back at all, so unfortunately I can't use this embed method currently.

Has anyone done this previously and if so would you mind sharing the steps you took?

Kind regards
Pete

**Comment by johnnephin** [comment]
+1 for an example

**Comment by GurdeepAulakh** [comment]
Hi There 

I have the same issue, is there any update on this, please?

**Comment by v-smahaj** [comment]
For FAQ Plus repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
