### ISSUE TITLE
Ask an Expert returns Unable to reach app. Please try again.

### ISSUE THREAD

**Issue by Sephiroth0327** [OfficeDev/microsoft-teams-apps-faqplus#52]
I have deployed the FAQ Plus app to Teams (I named it Ask SAM) and it seems to work fairly well.  But when I click "Ask an Expert" and fill out the form, I get the error below.  After triggering the error a handful of times, the bot now doesn't respond at all in Teams.  No responses to any messages.  Here are the things I have checked:

- On Config page, I confirmed that Team ID is set properly (I obtained value from going to Experts team and copying link to team)
- I am a member of the Experts team though I assume that shouldn't matter since the goal of this feature is to allow anyone to send a message to an Expert

![image](https://user-images.githubusercontent.com/69170603/89655690-781cbf80-d898-11ea-9156-1bd007c132d6.png)

One additional question - default Teams settings pops up a Card notification for the user for each response from the bot (see screenshot below).  These even appear if the user is sitting there using the bot - seems confusing as typically pop-up notifications are intended to appear when you are not already actively interacting with Teams.  How can we disable these at the bot level?

![image](https://user-images.githubusercontent.com/69170603/89667235-c7b7b700-d8a9-11ea-948b-ab7cce70fcc1.png)

**Comment by abbodh** [comment]
hi @Sephiroth0327 - can you please share the app insights telemetry failure logs when Ask an expert is called. If only Ask an expert command is failing, then my guess is either the expert team id is not configured correctly in configuration web app OR the FAQ Plus (Experts) application is not yet installed in expert team.

**Comment by Sephiroth0327** [comment]
@abbodh - Thank you for the response.  I ended up deleting the Experts app from the Team and then reinstalling it.  That resolved the issue.  Thanks!
