### ISSUE TITLE
Markdown formatting is not displaying properly in Teams

### ISSUE THREAD

**Issue by Sephiroth0327** [OfficeDev/microsoft-teams-apps-faqplus#55]
QnA KBs support rich text in Answers.  Rich text is achieved by using Markdown or by using the rich text editor.  When I try to use the Markdown below, it works fine when testing via the "Test" button on the QnA site.  However when I test in Teams, it is not formatted properly.  Please take a look.

**Code**
`[![Video](https://mydomain.sharepoint.com/sites/MyTraining/SiteAssets/ChatImages/WhatIsTeams.png)](https://www.youtube.com/watch?v=OxfukizkyCA)` (this is a clickable image which launches a video on Youtube)

This is how it appears in QnA:

![image](https://user-images.githubusercontent.com/69170603/89943962-1092a700-dbed-11ea-8614-4991662f2d10.png)

This is how it behaves in the QnA Test:

![image](https://user-images.githubusercontent.com/69170603/89944044-2e600c00-dbed-11ea-9861-d62e2e90ed95.png)

But this is what it looks like in Teams after being published:

![image](https://user-images.githubusercontent.com/69170603/89944170-60716e00-dbed-11ea-8cb9-b70af6e3776a.png)

**Comment by abbodh** [comment]
Hi @Sephiroth0327 , Teams application uses adaptive cards for showing bot response. Currently Teams adaptive cards supports limited markdown formats listed here - https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#formatting-cards-with-markdown

**Comment by Sephiroth0327** [comment]
> Hi @Sephiroth0327 , Teams application uses adaptive cards for showing bot response. Currently Teams adaptive cards supports limited markdown formats listed here - https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#formatting-cards-with-markdown

@abbodh - Thank you for the quick response.  I understand that Markdown has some limitations in Adaptive Cards.  Though I am confused as the bot comes preconfigured with image support.  If I type "Take a tour" then the response that comes back contains images.  How can I use this functionality?

**Comment by rafayanis** [comment]
Hi @Sephiroth0327 

I think you are facing the same issue as I described [here](https://github.com/OfficeDev/microsoft-teams-apps-faqplus/issues/54). I got the images to work, by using the JSON code. Or you can use the New Question option available in the Expert App. The only limitation is that if I display images, then the card is not supporting multi-turn options. You can try that if it works for you.

I believe that if we add an image (JSON code), teams pulls the response as Hero Card. Normally its pulling out the Adaptive Card to response, which doesn't support HTML as responded by @abbodh 

I believe it might be a matter of just updating the documentation or updating the bot to allow using multiple types of cards (if possible).

**Comment by Hickey77** [comment]
This is a major bummer (no pictures). The code above shows this for me in the card = no joy
![image](https://user-images.githubusercontent.com/54556057/97355286-1489a900-186d-11eb-8c38-2eb101cb1606.png)

**Comment by JeSuisUnCaillou** [comment]
Also facing the issue, images do not render in markdown format
![Screenshot from 2021-02-10 18-25-22](https://user-images.githubusercontent.com/6117264/107547232-83e19980-6bcd-11eb-960a-73ea6c4f1703.png)

**Comment by Hickey77** [comment]
Known PVA issue and will be addressed in H1 - https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-virtual-agents/add-images-videos-topics

In the meantime, can use this trick - https://powerusers.microsoft.com/t5/Webinars-and-Video-Gallery/Returning-an-image-as-a-message/td-p/575677

**Comment by JeSuisUnCaillou** [comment]
I just found a workaround, and possibly an explanation of the bug.

This is the url of my image, in the markdown I send in my markdown : 

> In my markdown
> `![image](https://canbot-jam.s3.amazonaws.com/2021-02-10/1612972263-capture_d___e__cran_2021-02-10_a___16.49.06.png)`

When I inspect my image in the teams web app and find its `src`, I can see it in the url param of a longer url, on skype.com :

> This image doesn't work
> https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fcanbot-jam.s3.amazonaws.com%2f2021-02-10%2f1612972263-capture_d___e__cran_2021-02-10_a___16.49.06.png

I imagine this is an asset hosting service, which hosts the image redirects to the hosted url. And I can see that this image is 401 forbidden in the console.

After a thousand tests, I ended up having a random image displayed, and when I inspected it I saw a different hosting domain in the `src` :

> This image works
> https://fr-prod.asyncgw.teams.microsoft.com/urlp/v1/url/content?url=https%3a%2f%2fparticuliers.engie.fr%2fcontent%2fdam%2fparticuliers-engie%2fphotos%2fhp%2fok-illu-aucun-parrainage.png

So I tried to force the same hosting domain by putting it myself before my image url :

> In my markdown
> `![image](https://fr-prod.asyncgw.teams.microsoft.com/urlp/v1/url/content?url=https%3a%2f%2fcanbot-jam.s3.amazonaws.com%2f2021-02-10%2f1612972263-capture_d___e__cran_2021-02-10_a___16.49.06.png)`

And it worked !

I guess `urlp.asm.skype.com` currently have some issues.

TL;DR : prefix your image url with `https://fr-prod.asyncgw.teams.microsoft.com/urlp/v1/url/content?url=`
(and encode the image url to be valid in the param, ofc)

**Comment by JeSuisUnCaillou** [comment]
> In the meantime, can use this trick - https://powerusers.microsoft.com/t5/Webinars-and-Video-Gallery/Returning-an-image-as-a-message/td-p/575677

@Hickey77 I saw your message after finding my own trick. Are your referring to the comment saying to host the images on blogger.com ?

**Comment by Hickey77** [comment]
No, not blogger.com.  Using a flow with no steps but a return variable that has markdown:  https://powerusers.microsoft.com/t5/Webinars-and-Video-Gallery/Returning-an-image-as-a-message/td-p/575677

@JeSuisUnCaillou
