### ISSUE TITLE
Not able to deploy faqplus-experts.zip

### ISSUE THREAD

**Issue by ErikHKnudsen** [OfficeDev/microsoft-teams-apps-faqplus#56]
Hi,

So I have been able to deploy the faqplus-enduser.zip bot. But when I try to add the faqplus-experts.zip to the correct Team, I get an error message saying "Something went wrong" (ref image). 
![image](https://user-images.githubusercontent.com/6149910/90231001-c1ca5480-de1a-11ea-9125-0fc0caed0cb5.png)

What I have tried so far is to:
* Recreate .zip file
* Download new manifest.json file
* Recreate manfiest.json file with Microsoft's template

Here is my .zip file with manifest, color and outline:
[faqplus-experts.zip](https://github.com/OfficeDev/microsoft-teams-apps-faqplus/files/5073498/faqplus-experts.zip)

Any ideas?

**Comment by GHNinja** [comment]
can you check 
- you using AppID from the user App for the botID value and not the config app. 
- Bot App Service's domain is [BaseResourceName].azurewebsites.net and not the config service domain
- icons file names in the .zip file matches the manifest file

**Comment by v-smahaj** [comment]
Let us know if this issue still persists.
