### ISSUE TITLE
Couldn't access the experts app tabs - Recent, Unassigned, and Assigned

### ISSUE THREAD

**Issue by berryst** [OfficeDev/microsoft-teams-apps-faqplus#59]
Hi I got the following error when trying to access the expert app tab tabs - recent, unassigned and assigned - it gave me the following message "Unable to reach app. Please try again."
i had a look at the Application Insight and found a lot of error related to the following

Failed to handle the messaging extension command composeExtension/query: An index with the name 'tickets-index' in service 'q4behcgfscauu-search' could not be created. Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.

<img width="452" alt="FAQExpertsError" src="https://user-images.githubusercontent.com/8452145/91935734-7ed90e00-ed42-11ea-955f-4a35ea3ff9d8.png">

**Comment by petecuttriss** [comment]
Hi @berryst , I'm seeing exactly the same thing.  Did you manage to get anywhere with this issue?

**Comment by petecuttriss** [comment]
Hi @berryst, I think I've fixed or found my issue in this case.  When I deployed the solution I choose the the F (3 indexes) Search Service Sku.  When the solution runs and you try and access the experts tab recent, unassigned, assigned it attempts to use the 'tickets-index' of the search service.   This index however doesn't exist as it hasn't been created.  The system isn't able to create the index as it is limited to 3 indexes and there were already three indexes.

I've redeployed my solution and this time I've chosen the B (15 inexes) option and I can now see that it has successfully created the 'tickets-index' within the search service and is working correctly.   

It might pay to check if you also chose the F (3 indexes) option during deployment.

![image](https://user-images.githubusercontent.com/4825764/92296078-cf3fae00-ef84-11ea-9b9a-10ee59e46e6d.png)

![image](https://user-images.githubusercontent.com/4825764/92296083-e1215100-ef84-11ea-8fdf-0752e4fc70eb.png)

**Comment by berryst** [comment]
Hi Peter, thanks for your help! I can see it's working now after changing the search service sku from F to B.. i was trying to avoid cost associated :) 
but now i've a seperate issue that i'll open on a new issue. thanks a lot!

**Comment by GHNinja** [comment]
where do i find these Experts assigned tabs ?

**Comment by petecuttriss** [comment]
> where do i find these Experts assigned tabs ?

Hi @GHNinja, the tabs that @berryst and I are referring to are found on the FAQ Experts App:
![image](https://user-images.githubusercontent.com/4825764/104509159-23068600-564e-11eb-8db1-bd7b6786d885.png)

https://github.com/OfficeDev/microsoft-teams-apps-faqplus/wiki

**Comment by GHNinja** [comment]
step where the doc says 
Expert invoking the task module to add QnA pair:

what you highlighted in above pic, i guess i am missing in my experts app,  
i need to review what i missed in the setup unless you can help me why i don't have them in my experts app ?
