### ISSUE TITLE
The Solution Overview Page Returns a 404

### ISSUE THREAD

**Issue by jameswh3** [OfficeDev/microsoft-teams-apps-faqplus#61]
On the Getting Started section of the readme.md file, the link to the solution overview appears to be broken:

![image](https://user-images.githubusercontent.com/4581067/92256147-f620b600-ee98-11ea-94c9-e43d5b81d76c.png)

The target for the link is: https://github.com/OfficeDev/microsoft-teams-apps-faqplus/blob/master/wiki/Solution-overview

**Comment by v-smahaj** [comment]
Thank you for reporting this, we have updated the link to Solution overview.
