### ISSUE TITLE
Knowledge base & Add new question not working

### ISSUE THREAD

**Issue by berryst** [OfficeDev/microsoft-teams-apps-faqplus#64]
i've got the following parts not working , knowledge base 
![image](https://user-images.githubusercontent.com/8452145/92348088-10bb8f00-f126-11ea-9090-e88cd24c2758.png)

Create a new question
![image](https://user-images.githubusercontent.com/8452145/92348101-1e711480-f126-11ea-80a9-e09440030add.png)

the end-user functionality seems to work as expected only the expert functionality especially these two parts that aren't working... appreciate any insight on how i can troubleshoot this error..thank you!

**Comment by chelito103** [comment]
I have the same type of issue.

**Comment by v-smahaj** [comment]
Thank you for reporting this. Seems like there would be some deployment issue. Please validate tenant Id in App Service configuration in Azure portal. It should be tenant Id of tenant where manifest is installed.
Please review other configuration values and manifest values as well. 
Let us know if issue still persists.
