### ISSUE TITLE
Getting error message " Unable to reach app. Please try again"

### ISSUE THREAD

**Issue by msantosh07** [OfficeDev/microsoft-teams-apps-faqplus#66]
I have deployed the BOT as per Github (https://github.com/OfficeDev/microsoft-teams-apps-faqplus/wiki/Deployment-Guide), but while entering the sending an request in TEAMS Chat as "Ask an Expert" getting below error message.
"Something Went wrong. Please try again later"
![error message](https://user-images.githubusercontent.com/70733648/94343768-268ee680-0038-11eb-8966-cfa16d98a37c.JPG)

**Comment by johnnephin** [comment]
I received this as well today after it was working for a few hours.  I uninstalled the apps in teams and re-added them and it worked.

**Comment by RuudZoutenbier** [comment]
Can you tell me the following.
Did you use de bot ID in the manifest_sme from the faqplus-config app or the facplus app.

**Comment by v-smahaj** [comment]
Seems like there would be some deployment issue. Please validate tenant Id in App Service configuration in Azure portal. It should be tenant Id of tenant where manifest is installed. 
Bot Id of FAQ Plus app should be added in manifest_sme and manifest_enduser.
Let us know if issue still persists.
