### ISSUE TITLE
Bot does not respond to user input

### ISSUE THREAD

**Issue by jeshall73** [OfficeDev/microsoft-teams-apps-faqplus#67]
After following the deployment guide and sideloading the app, we are unable to get it to respond to regular or expert team users. Azure Insights show some authentication failures, but we've double checked the appid and the app secret and they are correct. Please help!

**Comment by MihaiTCJ** [comment]
@jeshall73  Hello. We have the same problem. Have you managed to solve it ?

**Comment by v-smahaj** [comment]
Seems like there would be some deployment issue. Please validate tenant Id in App Service configuration in Azure portal. It should be tenant Id of tenant where manifest is installed.
Let us know if issue still persists.
