### ISSUE TITLE
Is there a way to add a Drop Down to the Adaptive card in Teams?

### ISSUE THREAD

**Issue by shanemeisner** [OfficeDev/microsoft-teams-apps-faqplus#69]
Our company is looking to use the FAQPlus bot but one aspect they would like is to add a "Topic" Dropdown to the "Ask the Expert" Card.. 
So that when a user click "Ask the Expert" besides the current fields, they would like us to add a Topic Dropdown that users would select predefined topics ( SharePoint, Outlook, Network, etc.) before it sends to the Experts.

Any thoughts on how to accomplish that?

**Comment by ahmedmahmoudR** [comment]
Is there any solution to this request ??

**Comment by v-smahaj** [comment]
For FAQ Plus repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
