### ISSUE TITLE
Issue Deploying FAQPlus Experts app to Teams

### ISSUE THREAD

**Issue by lakrupka** [OfficeDev/microsoft-teams-apps-faqplus#75]
Was able to successfully upload the FAQ Plus app but received an error when deploying the FAQ Plus Experts app. 

Screen shot of error and app zip file used for the upload are attached. 

[faqplus-experts.zip.zip](https://github.com/OfficeDev/microsoft-teams-apps-faqplus/files/5542881/faqplus-experts.zip.zip)

![Error msg](https://user-images.githubusercontent.com/50598974/99193138-9c602600-273c-11eb-9811-15619924cc37.png)

**Comment by Mikhail2k15** [comment]
Looks like you have a typing issue in manifest
![image](https://user-images.githubusercontent.com/11201670/99195776-e70f8b80-2798-11eb-8957-ee6dcbfa0302.png)

**Comment by lakrupka** [comment]
Excellent, thank you! I was able to correct the issue and successfully uploaded the app.
