### ISSUE TITLE
Error in Deployment in Microsoft.BotService/botServices/channels

### ISSUE THREAD

**Issue by makandmozart** [OfficeDev/microsoft-teams-apps-faqplus#76]
At the moment of making the deployment I get this error in
contosofaqplusdos / MsTeamsChannel:

{
    "status": "Failed",
    "error": {
        "code": "UnknownError",
        "message": "An unexpected error occurred. Exception: 'System.AggregateException: One or more errors occurred. ---> SkypeApsAdapter.SkypeApsAdapterException: Agent failed APS validation. ---> System.ArgumentException: UserTileExtraLargeUrl must use HTTPS.\r\n   at Microsoft.Skype.Platform.AgentProvisioning.Contracts.ValidationHelper.ValidateUrl(Uri uri, Boolean allowNull, String name, Boolean requireHttpsScheme) in D:\\a\\_work\\179\\s\\AgentProvisioning\\Contracts\\ValidationHelper.cs:line 84\r\n   at Microsoft.Skype.Platform.AgentProvisioning.Contracts.AgentValidation.Validate(AgentDescriptionSkypeChannel agentDescription) in D:\\a\\_work\\179\\s\\AgentProvisioning\\Contracts\\AgentHelper.cs:line 157\r\n   at Microsoft.Skype.Platform.AgentProvisioning.Contracts.AgentValidation.Validate(AgentSkypeChannel agent) in D:\\a\\_work\\179\\s\\AgentProvisioning\\Contracts\\AgentHelper.cs:line 149\r\n   at SkypeApsAdapter.ApsAdapter.MergeAndNewAgent(Agent2 existingAgent, BotService bot, String botHistoryType, Boolean trackExceptions) in D:\\a\\1\\s\\SkypeApsAdapter\\ApsAdapter.cs:line 130\r\n   --- End of inner exception stack trace ---\r\n   at SkypeApsAdapter.ApsAdapter.MergeAndNewAgent(Agent2 existingAgent, BotService bot, String botHistoryType, Boolean trackExceptions) in D:\\a\\1\\s\\SkypeApsAdapter\\ApsAdapter.cs:line 137\r\n   at SkypeApsAdapter.ApsAdapter.<CreateAgentWithSynchronizationAsync>d__2.MoveNext() in D:\\a\\1\\s\\SkypeApsAdapter\\ApsAdapter.cs:line 39\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at Intercom.Helpers.TaskUtility.PropagateExceptions(Task task) in D:\\a\\1\\s\\Utilities\\Intercom.Helpers.Extensions\\TaskUtility.cs:line 72\r\n   at Intercom.Helpers.Concurrency.<>c__DisplayClass3_0`1.<_handleStatusCodes>b__0(Task`1 antecedent) in D:\\a\\1\\s\\Utilities\\Intercom.Helpers.Tasks\\Concurrency.cs:line 61\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Intercom.Channels.Controllers.Skype.ApsAgentManager.<GetOrNewAgentAsync>d__3.MoveNext() in D:\\a\\1\\s\\Intercom.Channels\\Controllers\\Skype\\ApsAgentManager.cs:line 48\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Intercom.Channels.Controllers.Skype.ApsAgentManager.<UpdateOrNewAgentAsync>d__4.MoveNext() in D:\\a\\1\\s\\Intercom.Channels\\Controllers\\Skype\\ApsAgentManager.cs:line 65\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Intercom.Channels.Controllers.Shared.FirstPartyChannelConfigHelperBase`1.<UpdateSettingsAndAgent>d__15.MoveNext() in D:\\a\\1\\s\\Intercom.Channels\\Controllers\\Shared\\FirstPartyChannelConfigHelperBase.cs:line 180\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Intercom.Channels.Controllers.Shared.FirstPartyChannelConfigHelperBase`1.<UpdateConfigSettings>d__9.MoveNext() in D:\\a\\1\\s\\Intercom.Channels\\Controllers\\Shared\\FirstPartyChannelConfigHelperBase.cs:line 80\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at Intercom.ResourceProvider.Channels.TeamsArmChannelManager.<UpdateChannelCore>d__4.MoveNext() in D:\\a\\1\\s\\Intercom.ResourceProvider\\Channels\\TeamsArmChannelManager.cs:line 58\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at Intercom.ResourceProvider.Channels.BaseTypedArmChannelManager`3.<UpdateChannelAsync>d__8.MoveNext() in D:\\a\\1\\s\\Intercom.ResourceProvider\\Channels\\ArmChannelManager.cs:line 309\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at Intercom.ResourceProvider.DataProviders.ChannelResourceDataProvider.<InsertResourceAsync>d__9.MoveNext() in D:\\a\\1\\s\\Intercom.ResourceProvider\\DataProviders\\ChannelResourceDataProvider.cs:line 99\r\n---> (Inner Exception #0) SkypeApsAdapter.SkypeApsAdapterException: Agent failed APS validation. ---> System.ArgumentException: UserTileExtraLargeUrl must use HTTPS.\r\n   at Microsoft.Skype.Platform.AgentProvisioning.Contracts.ValidationHelper.ValidateUrl(Uri uri, Boolean allowNull, String name, Boolean requireHttpsScheme) in D:\\a\\_work\\179\\s\\AgentProvisioning\\Contracts\\ValidationHelper.cs:line 84\r\n   at Microsoft.Skype.Platform.AgentProvisioning.Contracts.AgentValidation.Validate(AgentDescriptionSkypeChannel agentDescription) in D:\\a\\_work\\179\\s\\AgentProvisioning\\Contracts\\AgentHelper.cs:line 157\r\n   at Microsoft.Skype.Platform.AgentProvisioning.Contracts.AgentValidation.Validate(AgentSkypeChannel agent) in D:\\a\\_work\\179\\s\\AgentProvisioning\\Contracts\\AgentHelper.cs:line 149\r\n   at SkypeApsAdapter.ApsAdapter.MergeAndNewAgent(Agent2 existingAgent, BotService bot, String botHistoryType, Boolean trackExceptions) in D:\\a\\1\\s\\SkypeApsAdapter\\ApsAdapter.cs:line 130\r\n   --- End of inner exception stack trace ---\r\n   at SkypeApsAdapter.ApsAdapter.MergeAndNewAgent(Agent2 existingAgent, BotService bot, String botHistoryType, Boolean trackExceptions) in D:\\a\\1\\s\\SkypeApsAdapter\\ApsAdapter.cs:line 137\r\n   at SkypeApsAdapter.ApsAdapter.<CreateAgentWithSynchronizationAsync>d__2.MoveNext() in D:\\a\\1\\s\\SkypeApsAdapter\\ApsAdapter.cs:line 39<---\r\n'."
    }
}

**Comment by v-smahaj** [comment]
Hi @makandmozart 
Were you able to resolve this issue?
Let us know if issue still persists.
