### ISSUE TITLE
Error with "Ask an Expert".

### ISSUE THREAD

**Issue by pfinkler** [OfficeDev/microsoft-teams-apps-faqplus#79]
We've deployed FAQ Plus and when using the bot, if someone clicks on "Ask an Expert", it throws an error saying, "Unable to reach app. Please try again".  I'm not sure what could be causing the problem.  Is this an issue with the Bot itself or on the Azure side of things?

**Comment by RuudZoutenbier** [comment]
I have the same problem. Is it possible that the BotID is wrong.
The deployment guide says to use the botID (faqplus) in the manifest_enduser.json and it says to repeat these steps in the manifest_sme. Do you use the same botID or the BotID of faqplus-config in the manifest_sme?

**Comment by GHNinja** [comment]
BotID of the user app must be used in both packages

**Comment by v-smahaj** [comment]
Seems like there would be some deployment issue. Please validate tenant Id and other configurations  in App Service configuration in Azure portal. It should be tenant Id of tenant where manifest is installed.
Let us know if issue still persists.
