### ISSUE TITLE
Something went wrong response

### ISSUE THREAD

**Issue by AlanMRichards** [OfficeDev/microsoft-teams-apps-faqplus#82]
Hi

I have managed to deploy the bot and everything seems to work, tour ask an expert but when I ask it a question it just responds with Something went wrong. Try again later. I have checked the manifest file, uninstalled, reinstalled but still get the same error.

I have run out of ideas apart from redeploying the whole thing from scratch

**Comment by v-smahaj** [comment]
Seems like there would be some deployment issue. Please validate tenant Id in App Service configuration in Azure portal. It should be tenant Id of tenant where manifest is installed.
Let us know if issue still persists.
