### ISSUE TITLE
Typo in deployment guide

### ISSUE THREAD

**Issue by dostakin** [OfficeDev/microsoft-teams-apps-faqplus#84]
In step 11 of "Step 6: Create the Teams app packages"	reads:

> Name this package faqplus-experts.zip, so you know that this is the app for end-users.

Should instead read
Name this package faqplus-experts.zip, so you know that this is the app for **experts**.

I think it is a typo because it is similar step 6 which reads:

> Name this package faqplus-enduser.zip, so you know that this is the app for end-users.

**Comment by v-smahaj** [comment]
Thank you for reporting this. We have updated the deployment guide to take care of above issue.
