### ISSUE TITLE
QnAMaker released new version. 

### ISSUE THREAD

**Issue by dvzalagaev** [OfficeDev/microsoft-teams-apps-faqplus#85]
Can we somehow switch into using New version of QnAMaker?

New version is way much better. But I could find a way to point my existing FAQ Plus to the new KB.

**Comment by cankanat** [comment]
You can create new knowledge base manually and then you must change bot app service, function, and cofig app parameters with new QnA maker and Search service keys, endpoint and url's from configuration section.

For instance when you create a new KB you should get new config parameters from azure portal and qnamaker.ai

**From qnamaker.ai:**

- Knowledge Base ID
- Host
- EndPointKey

**From portal:**

**Search Service > Keys and Endpoint**

- Search Service Name
- Primary Key
- Key

**QnA Service > Keys and Endpoint** 

- EndPoint URL
- Key 1

and then you should navigate one by one to your app service, function, app service of config app's configuration menu and change the parameters below with the new paramaters. And also, update the ConfigurationTable in storage account with the new knowledebase id and key.

**AppService > Configuration**

- QnAMakerApiEndpointUrl
- QnAMakerHostUrl
- QnAMakerSubscriptionKey
- 
- SearchServiceAdminApiKey
- SearchServiceName
- SearchServiceQueryApiKey

**Function > Configuration**

- QnAMakerApiUrl
- QnAMakerSubscriptionKey
- SearchServiceAdminApiKey
- SearchServiceName
- SearchServiceQueryApiKey

**App Service (Config) > Configuration**

- QnAMakerApiEndpointUrl
- QnAMakerSubscriptionKey

**Storage > Inside ConfigurationTable**

- QnaMakerEndpointKey
- KnowledgeBaseId
