### ISSUE TITLE
Unable to reach app. Please try again.

### ISSUE THREAD

**Issue by NRG-Me** [OfficeDev/microsoft-teams-apps-faqplus#87]
When trying to leverage the FAQ Plus (Experts Team) , I get the error "unable to reach app. please try again".  I was able to install both the apps for FAQ Plus (Experts Team) and also the FAQ Plus end-users app in the admin portal.  I have double checked that the manifest files have the right attributes.  What am I missing?

**Comment by v-smahaj** [comment]
Seems like there would be some deployment issue. Please validate tenant Id in App Service configuration in Azure portal. It should be tenant Id of tenant where manifest is installed.
Let us know if issue still persists.
