### ISSUE TITLE
Whitelisted URLs

### ISSUE THREAD

**Issue by rhajj19** [OfficeDev/microsoft-teams-apps-faqplus#89]
Hello, can you please provide us with the whitelisted URLS as we are getting an error of Something went wrong during our deployment. Can you please assist us in the below ?
![something went wrong](https://user-images.githubusercontent.com/74534591/108623072-ffeda400-744d-11eb-9840-9f9bfe86d39e.jpg)

**Comment by v-smahaj** [comment]
Can you share more details about the issue, so that we can guide you accordingly.
