### ISSUE TITLE
[enhancement] Request multilanguage support for BOT interface

### ISSUE THREAD

**Issue by antoniopanella** [OfficeDev/microsoft-teams-apps-faqplus#90]
Our client requested a change of the bot interface to Italian.

I see there is a pull request active to handle multilingual resx files.
I noticed that the file for the Italian language does not exist in the pull request.
Can we create the file by ourselves? If so, can you explain how?

**Comment by v-smahaj** [comment]
Our feature team is working on localization support for this app and planned to release in this quarter.
