### ISSUE TITLE
knowledgebase id is not valid.

### ISSUE THREAD

**Issue by dheevar** [OfficeDev/microsoft-teams-apps-faqplus#93]
Hi.

I am getting the "The provided knowledgebase id is not valid." message while setting the configuration app parameters. I have deleted and redeployed the entire solution quite a few times now but i still get the same error. all solution components have been deployed in the same Azure region.

I tried again the next day too just incase it take time to apply the settings but the same error.

Request you to let me know what could be the issue.

![image](https://user-images.githubusercontent.com/81696067/113158252-41e1e500-9259-11eb-83ec-088195f0e7bb.png)

**Comment by chelito103** [comment]
I had this issue, make sure that the knowledge base you created is on the same subscription that you have associated to the QnA service.

**Comment by dheevar** [comment]
Yes it is. I have verified the same.

Regards,

Dheevar Paralkar.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by v-smahaj** [comment]
Please verify if Knowledge base is created in same Cognitive service which was created during ARM deployment. 
Check QnAMakerHostUrl in App Service configuration. Knowledge base should be created inside same QnA Maker which is referred in App Service configuration.
Let us know if issue still persists.

**Comment by dheevar** [comment]
> Please verify if Knowledge base is created in same Cognitive service which was created during ARM deployment.
> Check QnAMakerHostUrl in App Service configuration. Knowledge base should be created inside same QnA Maker which is referred in App Service configuration.
> Let us know if issue still persists.

Hi,

I have verified that all the services are deployed in the same subscription, region and other points which you have mentioned.
