### ISSUE TITLE
Expert reply as not a direct message

### ISSUE THREAD

**Issue by tdenny171202** [OfficeDev/microsoft-teams-apps-faqplus#95]
Hello,

Is it possible for the expert reply to happen from within the app that our end users are downloading or is direct communication for issue resolution the only option with this kind of bot?

**Comment by v-smahaj** [comment]
For FAQ Plus repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
