### ISSUE TITLE
ScoreThreshold Update

### ISSUE THREAD

**Issue by cankanat** [OfficeDev/microsoft-teams-apps-faqplus#96]
How can I update the ScoreThreshold to 80% ?

**Comment by v-smahaj** [comment]
Please follow below steps for updating score threshold:

1. Login to Azure subscription where app is deployed.
2. Select App Service which was created during ARM deployment.
3. Once App Service is opened, click on Configuration in left navigation pane.
4. Update ScoreThreshold value to 0.8 for 80%.

**Comment by cankanat** [comment]
It's not working. I updated ScoreThreshold to 0.7 but the bot answers the question with %54 confidence score in some qna pairs.

**Comment by Mikhail2k15** [comment]
@cankanat looks like the QnAMaker REST API was changed. Could you try to specify 70 instead of 0.7?

**Comment by cankanat** [comment]
Thank you very much @Mikhail2k15 Now it works.
