### ISSUE TITLE
Issue on AdaptiveChoiceSetInput design, on mobile app dropdown first value having strike line, when we tab on it

### ISSUE THREAD

**Issue by bikkykumar1** [OfficeDev/microsoft-teams-apps-faqplus#97]
Hello Team, I am facing one design issue over Teams mobile app, it is working fine on Desktop version.

Getting design issue on AdaptiveChoiceSetInput control on AdaptiveCard

I am getting a strike line when i tab on the dropdown over mobile, a strike line similar to 'v' shape

`AdaptiveChoiceSetInput choiceSet = new AdaptiveChoiceSetInput { Id = "dropdownuniqueID", IsMultiSelect = false, Style = AdaptiveChoiceInputStyle.Compact 
};`

**To reproduce:**
please open the SME card in Android mobile and click on 'Change Status' button on behalf of Expert. and when you tab on the dropdown value will expand in the screen and on that the first value having a strike line.

**Sorry team not able to upload any snapshot getting below error on developer tool**
Access to XMLHttpRequest at 'https://github-production-user-asset-6210df.s3.amazonaws.com/' from origin 'https://github.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by v-smahaj** [comment]
We are not able to reproduce this issue at our end.
Can you share screenshot and mobile screen size.
